### ISSUE TITLE
Premios Sábado, mayo 20 5:20pm, en el Stand GitHub DevOpsDays Medellin

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#1]
### SORTEO DESPUES DE LA CHARLA DE COPILOT X SALA 1 AUDITORIA PRINCIPAL

Para participar en este sorteo de swag solo tienes que dejar un comentario en este issue ⬇️
¡Únete a nuestro [Meetup en español](https://www.meetup.com/githublatam/) y sé parte de nuestra comunidad! Si deseas compartir tus conocimientos como ponente, te invitamos a enviar tu propuesta de charla a través de [este enlace](https://githubmeetup.typeform.com/to/LWlStlet). ¡Estamos emocionados por conocer tus ideas y enriquecer juntos esta experiencia!
Buena Suerte!

### Premio Mayor
![IMG_0557](https://github.com/githubpresente/selector-rifa/assets/20666190/eb520cf5-0f68-41be-82b0-7f02e7c5ef96)

**Comment by ag1111** [comment]
test3

**Comment by vanessamarely** [comment]
Github presente en DevopsDays Medellin 🌟😊💪🏻

**Comment by calypsobronte** [comment]
NodeCo presente en DevOps

**Comment by michamoro** [comment]
Hola, quiero ganarme ese premio tan bello. Saludos
Git bye.

**Comment by jhohan97** [comment]
Hola, ese premio esta genial, lo quiero ganar !!

**Comment by 4dagio** [comment]
Presente el DOD #3 #4, fix: lights!

**Comment by edcalderon** [comment]
Genial!!!

**Comment by edcalderon** [comment]
🤯❤️‍🔥👽🤖

**Comment by RamirezCO20** [comment]
Hola, el premio está genial, quiero participar!

**Comment by Jose-Rivas-L** [comment]
¡Yo quiero participar!

**Comment by Broncos225** [comment]
¡Yo quiero participar!

**Comment by diazrendoncesar9** [comment]
Great....

**Comment by AdrianPerdomoE** [comment]
Ojalá gane algo :crossed_fingers:

**Comment by santiago-perez-ruiz** [comment]
Con toda en este #DODMedellin

**Comment by wacGitHub07** [comment]
Hola, participando en la rifa 🤘

**Comment by jopetech** [comment]
Hola, vamos a por todas

**Comment by JULIANCHO923** [comment]
Hola DevOpsDays Medellin 2023

**Comment by trebol256** [comment]
Presente en DevOps Day

**Comment by luis-giraldo** [comment]
🙋‍♂️

**Comment by ingjulioreyes** [comment]
#dodmedellin 2023

**Comment by jotaherrera** [comment]
👨‍💻

**Comment by santiblanko** [comment]
Está muy interesante el evento

**Comment by russbelln** [comment]
Presente en el DevopsDay Medellín 2023!!!

**Comment by eligregl** [comment]
Presente en DevOpsDays2023!

**Comment by lggaleanor** [comment]
Devops med el mejor!!

**Comment by jdiegoisaza** [comment]
Presente en el DevOpsDay

**Comment by anromanv** [comment]
Presente en DevOps Days Medellín, gracias GitHub Presente!! ✌🏻🚀

**Comment by kevinRG27** [comment]
Go #DODMEDELLIN 2023

**Comment by anromanv** [comment]
Presente en el DevOps Days, gracias a Github Presente 🚀💫

**Comment by ManuelCarrascal** [comment]
Github en devOpsDays medellín 2023

**Comment by StudentUCO** [comment]
DevOpsDay Medellín

**Comment by erazo2498** [comment]
DevOpsDays Medellín 2023, el futuro es hoy

**Comment by kmilo07** [comment]
DevOpsDay Medellín 2023

**Comment by SantiagoMedinaNRA** [comment]
Presente en DOD! El premio está genial 😃

**Comment by enrique21** [comment]
Presente en DevopsDays Medellín 🤓

**Comment by andreycas** [comment]
Melo presente para la participación en medallo ome!

**Comment by IngCristhian** [comment]
Más tarde paso por mi premio, yo se que voy a ganar ! Jeje

**Comment by victo-rangel** [comment]
DevOps Day Medellín 🤞🏿

**Comment by ghost** [comment]
Segundo día presente en el DevOpsDays súper feliz de estar acá y venir al stand de GitHub me hace aún más feliz!

**Comment by AngieCard** [comment]
Acá en DevOpsDays💪🏾💪🏾

**Comment by Danifan1217** [comment]
Vamos GitHub poneme a ganar

**Comment by Karinaelena** [comment]
Hoy voy a ganar. Devopsday Medellín 2023

**Comment by Diego-Gil** [comment]
Hola, voy ganar el premio.... Gracias  DevOpsDay Medellín 2023,  y GitHub...

**Comment by lbedoyas** [comment]
quieroGanarElPremio(DevOpsDay): notificationGitHub

**Comment by jopetech** [comment]
#DODMedellin Vamos a por todas

**Comment by redux-mauricio-sanchez** [comment]
A ganar en el DODMed 😼

**Comment by faportes** [comment]
Excelente

**Comment by andri0015** [comment]
DevOps Days Medellín :)

**Comment by chrisvas6470** [comment]
DevOps Days Medellín

**Comment by jiflorez** [comment]
Presente DevOps Days Medellín

**Comment by bernardocastroa** [comment]
GitHub + Microsoft la mejor estrategia DevSecOps

**Comment by jcoelho** [comment]
Súper tenerlos participando en DevopsDays Medellín!

**Comment by carocastanedac** [comment]
Presente en el Devops Days Medellin 🙌💙

**Comment by dinareales** [comment]
Devops day Medellín

**Comment by astridtorres21** [comment]
Día dos en DevOps Days Medellín 👋

**Comment by yulian-zapata** [comment]
Presente en #DoDmedellin

**Comment by cristianregino** [comment]
#GitHub presente en el #DevOpsDays #Medellin

**Comment by Vrilli** [comment]
GitHub presente en el **DevOpsDayMedellin**

**Comment by verordgz25** [comment]
Gracias GitHub por la oportunidad 💕

**Comment by posorioe** [comment]
Github es genial. Presente en el DevOps Day y optimista a ganarme el premio 🥰

**Comment by heimarvega** [comment]
Holaaa soy Heimar Vega

**Comment by rcuan1979** [comment]
Voy por ese premio!!!

**Comment by pabloandresmelo** [comment]
Hola!!!!! Quiero ese swag ❤️

**Comment by cmgm15** [comment]
Holi

**Comment by crissando** [comment]
Cristhian Sandoval 😌

**Comment by judero01col** [comment]
Presente en DevOpsDays Medellin

**Comment by igacifuentes** [comment]
Giovanny Presente en el DevOps Day Medellin 🤘

**Comment by derocox** [comment]
Seré el ganador 😸

**Comment by malejin23** [comment]
#DOD MedeGit 😺🤟

**Comment by mateopineda** [comment]
#DODGitHub

**Comment by salvadorcastro19** [comment]
Git✅ and #DevOpsDayMedellin

**Comment by felopezm** [comment]
Gracias GitHub por estar en #DevOpsDaysMedellin 😎

**Comment by jecarvajal** [comment]
Presente en la DevOps day !

**Comment by jdaar** [comment]
DevOpsDays Medellin

**Comment by ChristYela** [comment]
Attending DevOpsDaysMDE2023 at UDEM

**Comment by Annaseanna** [comment]
Apenas para la sala de sistemas de la UN

**Comment by mmedinar** [comment]
DOD Medellín

**Comment by estebancatano** [comment]
#DODMedellin

**Comment by JULIANCHO923** [comment]
Hello DevOps Days

**Comment by JULIANCHO923** [comment]
Hello AndreaGriffiths11

**Comment by JULIANCHO923** [comment]
En hora Buena codespaces 😎

**Comment by ghost** [comment]
Amo docker y GitHub!

**Comment by AaronGonzalezB** [comment]
Genial codespaces! Lo voy a probar

**Comment by IngCristhian** [comment]
Esperando la hora para ir a recoger mi premio jeje 🥺 #DevopsDayMedellin 🤓

**Comment by IngCristhian** [comment]
😨😨 que interesante CodeSpaces !!

**Comment by DieberRoa** [comment]
Que lindo eso!

**Comment by lajuruiz** [comment]
Seré la ganadora 🚀

**Comment by Leo-Avalos** [comment]
I have found the things 🐱🐙

**Comment by wilmargarciav** [comment]
#DevOpsDays 🥸

**Comment by Eliana-Janneth** [comment]
Devops day Medellín 🤩

**Comment by die2aj** [comment]
Yo voy a ser el ganador 😎😎😎!! Presente en DevOps Days 2023!!

**Comment by JNPalomino** [comment]
Presente! DevOps days! ❤️

**Comment by matheovr** [comment]
Amo git hub!!! Muy amable y tesa!! Andrea, espero ganar el premio 🥰🥰🥰

**Comment by LordArshen** [comment]
GitHub DevOps days 2023

**Comment by NicoAV2311** [comment]
Listo para el concurso 🇨🇴

**Comment by alejandrarpo** [comment]
Listos para el sorteo!!

**Comment by Nelavers3** [comment]
Presente en Devops days Medellin 2023 l

**Comment by bernardocastroa** [comment]
![20230520_150745](https://github.com/githubpresente/selector-rifa/assets/111817173/5e8a953d-e87c-4276-9b5e-768669996011)
Andrea you rock!

**Comment by darklopera** [comment]
Presente desde la @devopsmedellin, gracias

**Comment by alejahenaoes** [comment]
Fan de la comunidad! ![IMG_7298](https://github.com/githubpresente/selector-rifa/assets/76217198/e5fcbe56-e15c-40fd-9414-04f7c49418dd)

**Comment by jmpine07** [comment]
Con toda la actitud para ganar en este DevOps Days - Medellin 2023

**Comment by jmpine07** [comment]
Con toda la actitud para ganar en este DevOps Days - Medellin 2023

**Comment by linavallejo** [comment]
Devops Conf 🥰🥰

**Comment by EdPrado4** [comment]
Presente en devopsdays medellin

**Comment by manolopajaro** [comment]
Vamos por ese premio!

**Comment by giancarlosmahecha** [comment]
DevOps Day Medellin.

**Comment by trebol256** [comment]
Hola, quiero concursar

**Comment by Alejopalaciog** [comment]
Que grande github!!!

**Comment by vyolete** [comment]
GitHub nos facilita la vida 😺🫶

**Comment by anubys17** [comment]
Aquí presente en el DevOps day. Genial todo!!!

**Comment by verordgz25** [comment]
Quiero el sorteo

**Comment by slayfer-dev** [comment]
Devopsday 2023

**Comment by alsoxavi** [comment]
Óscar presente en devops days! Github rules

**Comment by Mila-Ag** [comment]
Presente en el DevOpsDay con Github 😁

**Comment by Leita2013** [comment]
Presente en DevOps Day Medellín 2023.

**Comment by Sekaitsu** [comment]
Presente en la DevOps Medellín 2023 disfrutando del evento :D

**Comment by Krvaquiro** [comment]
DODMedellín

**Comment by alexrestrej** [comment]
Presente en DevOps Days Medellín 2023

**Comment by astridtorres21** [comment]
Por si acaso nuevamente presente día 2 DevOps Days Medellín

**Comment by jhonnatangilchavesGlobant** [comment]
Por aca JhonnyPong presente!!

**Comment by elizsumo** [comment]
Devops days med 2023 con Github

**Comment by Yarime21** [comment]
Carime... ARUS presente

**Comment by Jmilenita** [comment]
Voy a ganar en el devops day

**Comment by jullieth705** [comment]
Presente en el devops day Medellín!!!

**Comment by Ezfa** [comment]
Increíble toda la información, encantada de este mundo. 💕

**Comment by elmalba** [comment]
Yo me lo gano si o si

**Comment by jogazi** [comment]
Thanks GitHub for these presentations #DODMedellin

**Comment by Mteheran** [comment]
Yo me lo gano

**Comment by jmpine07** [comment]
Con actitud para ganarme el premio en este DevOps Days Medellin 2023

**Comment by j8danymono** [comment]
Ganar

**Comment by jcazolag** [comment]
DevOps Days Medellin 2023 
Juriana Gomez

**Comment by krmirezcasas** [comment]
Espero ganarme el premio en el DevOps Days Medellín 2023 versión 4 🤩

**Comment by ferchosur** [comment]
Presente en DevOpsDays Medellín! 

Fernando Giraldo

**Comment by eliblandon15** [comment]
Devopsday el mejor evento!

**Comment by SofiaSanchezGarrido** [comment]
Presente en el DevOps Day... Sofi 😍

**Comment by jruiz16** [comment]
Presente en el devops day, vamos por los premios

**Comment by SofiaSanchezGarrido** [comment]
DevOps Day... Aprendiendo constantemente

**Comment by edwarq** [comment]
Voy a Ganar !!!!!

**Comment by EdPrado4** [comment]
Presente en devopsdays medellin con github

**Comment by krlosjn** [comment]
DevOps days

**Comment by wilder16** [comment]
DevOps days son los mejores

**Comment by jeilow** [comment]
Hey genial github y su participación en Devops medellin!

**Comment by Leita2013** [comment]
Presente en DevOps Day Medellín

**Comment by JULIANCHO923** [comment]
DevOps rules

**Comment by JULIANCHO923** [comment]
DevOps Days rules

**Comment by JULIANCHO923** [comment]
Hola mamá estoy triunfando

**Comment by JULIANCHO923** [comment]
Esto no es un spam Este es un mensaje ganador

**Comment by JULIANCHO923** [comment]
Hola quiero El play 5 🤭🤭🤭

**Comment by fredypinto** [comment]
Hola quiero el gato ❤️

**Comment by JULIANCHO923** [comment]
GitHub copilot podria explotar las vulnerabilidades de cualquier Codig fuente que le pase 😐 en estos momentos no hay una respuesta de como evitarlo 🤔

**Comment by hvbarrios** [comment]
Copilot lo mejor

**Comment by derocox** [comment]
Rocket Copilot 🚀🚀🚀

**Comment by Jmilenita** [comment]
Voy a ganar

**Comment by edcalderon** [comment]
😇

**Comment by edcalderon** [comment]
😄

**Comment by edcalderon** [comment]
🤗

**Comment by santiago-perez-ruiz** [comment]
Vamoss

**Comment by hvbarrios** [comment]
Github excelente

**Comment by santiago-perez-ruiz** [comment]
Participando

**Comment by ghost** [comment]
I want to win

**Comment by jdiegoisaza** [comment]
![IMG_20230520_174301.jpg](https://github.com/githubpresente/selector-rifa/assets/39199649/177139a2-c217-44d0-b603-0279bb5d39bf)

Presente en el devops days

**Comment by SofiaSanchezGarrido** [comment]
A ganarrrrr

**Comment by ghost** [comment]
I win

**Comment by Jmilenita** [comment]
Presente

**Comment by edcalderon** [comment]
No

**Comment by JULIANCHO923** [comment]
Lucky cat

**Comment by ManuelCarrascal** [comment]
Vamos con toda

**Comment by edcalderon** [comment]
Im

**Comment by AranzalesO** [comment]
Me lo quiero ganar

**Comment by lbedoyas** [comment]
Quiero ganar el premio 
![IMG_20230520_142439_996](https://github.com/githubpresente/selector-rifa/assets/23284076/081e768f-c29c-4d31-ae13-d50601671fb9)

**Comment by Leita2013** [comment]
Haciendo fuerza por el premio

**Comment by edcalderon** [comment]
😶‍🌫️

**Comment by hvbarrios** [comment]
Excelente capacitación

**Comment by erazo2498** [comment]
Yoo, quiero de eso

**Comment by JULIANCHO923** [comment]
Broncos

**Comment by JhonierCordoba** [comment]
.Net forever

**Comment by Karinaelena** [comment]
Excelente

**Comment by JULIANCHO923** [comment]
Para que sirve esa Luz?

**Comment by ghost** [comment]
I am a winner

**Comment by hvbarrios** [comment]
Excelente

**Comment by almoralita** [comment]
DevOps Days Medellín !!

**Comment by JULIANCHO923** [comment]
Trebol

**Comment by ghost** [comment]
Win win ein

**Comment by SofiaSanchezGarrido** [comment]
Lo mejor

**Comment by almoralita** [comment]
Winner

**Comment by winsortf** [comment]
Saludos, soy Eydrent

**Comment by AndreaGriffiths11** [comment]
¡Muchas gracias por tu participación! ¡Nos vemos en el próximo [GitHub Presente!](https://www.meetup.com/githublatam/events/293146581)
