### ISSUE TITLE
Como cambiar el idioma del examen ?

### ISSUE THREAD

**Issue by Slaif3r** [gittogethers/selector-rifa#186]
`Hola disculpen tengo un conocido que tiene un **Issue** de verdad, es que cuando fue a programar el examen no le pregunto en que idioma deseaba tomarlo y el examen quedo programado en ingles, nos preguntabamos si era posible cambiar de idioma para hacer el examen en español? @mageroni , agradezco el apoyo que puedas brindarnos !!!`

**Comment by AndreaGriffiths11** [comment]
Hola! El examen es en ingles, lo siento
