### ISSUE TITLE
Meetup @Mill5

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#2]
Para participar en este sorteo de swag solo tienes que dejar un comentario en este issue ⬇️
¡Únete a nuestro [Meetup en español](https://www.meetup.com/githublatam/) y sé parte de nuestra comunidad! Si deseas compartir tus conocimientos como ponente, te invitamos a enviar tu propuesta de charla a través de [este enlace](https://githubmeetup.typeform.com/to/LWlStlet). ¡Estamos emocionados por conocer tus ideas y enriquecer juntos esta experiencia!
Buena Suerte!

**Comment by AndreaGriffiths11** [comment]
testing 1

**Comment by dsolartec** [comment]
Hola

**Comment by DavidJimenez10** [comment]
Hola

**Comment by vanessamarely** [comment]
Hola! 🌟 github presente 👍

**Comment by david4tech** [comment]
Hello GitHub

**Comment by daniel-monsalve-villegas** [comment]
hola

**Comment by camilogruiz** [comment]
Hola!

**Comment by filgaia** [comment]
GitHub presente con la influencer @vanessamarely

**Comment by davidkasta87** [comment]
Hola, desde Medellín, con el amigo de la influencer

**Comment by Angelfire** [comment]
Hi!

**Comment by RedLavaEye** [comment]
Que buen espacio. Gracias Github Presente !

**Comment by notpidro** [comment]
Vamoooss ! Estoy mirando el evento desde Twitch

**Comment by yazminr4** [comment]
Hi😊
