### ISSUE TITLE
Open Source Viernes con Miguel Raz

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#24]
¡Deja un comentario para participar en la rifa! Solo dentro de este issue. Y aquí te compartimos el [enlace](https://www.youtube.com/live/LSCyJUYFADs?feature=share) del video, recuerda unirte a nuestro [Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a) y seguir a [Miguel](http://twitter.con/miguelraz_) en sus redes.

- Ya usaste Rust?

**Comment by ag1111** [comment]
Si!

**Comment by andresovalle8** [comment]
No pero motivado a aprender gracias Miguel Raz

**Comment by mgaligniana** [comment]
No he usado!

Muchas gracias por los streams!

**Comment by ezestom** [comment]
Un espectáculo los viernes de Open Source, ❤️ Gracias GitHub & Microsoft!

**Comment by johiny** [comment]
Hola!
No lo he usado pero en las esferas del front-end no paro de escuchar como todos los bundlers lo están adoptando para mejorar velocidades en todo, también he escuchado que lo está adoptando Linux con todo eso rust debe ser un monstruo

**Comment by vidal1101** [comment]
aun no, pero ya me genero curiosidad por aprender y explorar que puedo lograr para aporte de la comunidad. Dont stop Learning.

**Comment by dipatricia** [comment]
Todavia no lo he utilizado.

**Comment by LuceroLuciano** [comment]
¡Hola!👋 
No, no sabia de su existencia, acabo de descubrirlo. 
Gracias GitHub por los eventos y espacios para seguir aprendiendo💜

**Comment by lizarragadev** [comment]
Rust es vida , Rust es amor 😎

**Comment by AndreaGriffiths11** [comment]
Felicidades @ezestom, por favor escríbeme a andreagriffiths11@github.com para recibir tu premio 
<img width="894" alt="Screenshot 2023-07-07 at 11 14 07 AM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/4541b3a7-3ae2-4da5-9730-2e5160411322">
