### ISSUE TITLE
AI Martes con Platzi

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#25]
<img width="897" alt="Screenshot 2023-07-18 at 2 38 33 PM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/336c1876-59f0-478f-9446-c5560b210696">
¡Deja un comentario para participar en la rifa!

 **SOLO** dentro de este issue, no habrás un issue nuevo.

Y aquí te compartimos el [enlace de recursos](https://github.com/githubpresente/IA-estudio) de la presentación de hoy, y no olvides unirte a nuestro [Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).

¿Ya usaste GitHub Copilot?

**Comment by SylvesterStandallone** [comment]
Hello!

**Comment by KevinJohao** [comment]
Holaaa

**Comment by gilbertoesp** [comment]
Hello, Hola. Presente en el vivo aprendiendo de la revolución IA

**Comment by kevinandresforero** [comment]
Que orgullo tener gente colombiana en puestos altos en github y orgullo extra mujer¡¡¡

**Comment by samucodesh** [comment]
Hola Andrea gracias por todo lo que aportas al Open Source

**Comment by jacastrorug** [comment]
Hola!

**Comment by eVillator** [comment]
Gran charla Andrea Griffiths, thanks a lot.

**Comment by JaquelineTorres** [comment]
¡Hola a todos (^^)/!

**Comment by DonovanAC7** [comment]
Saludos desde Guatemala!

**Comment by majomarquez** [comment]
Holi!!! Gracias por el en vivo!!☺️

**Comment by jefercanya** [comment]
Hello!!
🤯

**Comment by acbcdev** [comment]
hola

**Comment by Jzea94** [comment]
💚

**Comment by bazadrian** [comment]
hola

**Comment by davissaix** [comment]
AI is exciting

**Comment by Tommybg** [comment]
Nueva experiencia del desarrollador para un nuevo desarrollador. 👀🚀😉 
Create impact leveraging AI and human collaboration 🚀🚀🚀

**Comment by 6erman** [comment]
Hola ... Aún no he usado copilot.... Lo usaré al terminar el reto de 21 días de Python

**Comment by NmunizWizeline2022** [comment]
Hola desde Mexico

**Comment by LuisBourbaki** [comment]
Saludos desde México 🇲🇽

**Comment by eduardoemt1** [comment]
Prestando toda la atención desde Cali, Colombia.

**Comment by areyesa86** [comment]
Saludos desde la Ciudad de México.

**Comment by Supermilotito** [comment]
Saludos desde Monterrey  🌄 :D

**Comment by Kiefer-Jurgen-Curiel-Diaz** [comment]
Muy buenas tardes, que interesante martes de IA que tendremos esta ocasión. Sera un gusto aprender una nueva lección para avanzar en nuestro desarrollo personal junto con la ayuda de la IA.

**Comment by garvizleo12** [comment]
Saludos desde Chile.

**Comment by Oscarfe** [comment]
Saludos desde New York.

**Comment by edupr** [comment]
Hola amigos!! 👋

**Comment by sebasmolinat** [comment]
Saludos desde Colombia.

**Comment by huacamx** [comment]
escribieron mal platzy!? Prbando copilot

**Comment by fholken** [comment]
Excelente estas charlas !!!

Utilizo Copilot en algunos casos, para generar pruebas unitarias

**Comment by cesarortizgit** [comment]
Andrea,  excelente charla la que diste en platzi, Felicidades

**Comment by camilotayo** [comment]
Creo firmemente que la IA no nos reemplazará, pero nos potenciará 🙂

**Comment by lcarloszapatag** [comment]
Hello andrea.Thanks teacher for Martes de IA

**Comment by ubaldogs** [comment]
Hey hola!

**Comment by SoyEdwinCabrera** [comment]
Saludos desde Colombia

**Comment by JeanPierrelive** [comment]
Hola desde Colombia

**Comment by Tommybg** [comment]
Nueva experiencia del desarrollador para un nuevo desarrollador. 👀🚀😉 
Create impact leveraging AI and human collaboration 🚀🚀🚀

**Comment by Cristeph2** [comment]
Hola hola :)

**Comment by Tommybg** [comment]
Nueva experiencia del desarrollador para un nuevo desarrollador. 👀🚀😉
Create impact leveraging AI and human collaboration 🚀🚀🚀

**Comment by ayenque** [comment]
Hola! Escuchando los martes de IA

**Comment by Krax7** [comment]
Hola!! Saludos, Andrea y saludos a todos :)

**Comment by Tommybg** [comment]
Nueva experiencia del desarrollador para un nuevo desarrollador. 👀🚀😉
Create impact leveraging AI and human collaboration 🚀🚀🚀

**Comment by joseeverm** [comment]
Jamàs pararemos de aprender 💻

**Comment by evallesv** [comment]
👋🏼 excelente muchas gracias

**Comment by Alucia** [comment]
Entre tarde a la charla, pero me encanto conocer mas acerca de github copilot, saludos desde Perú, gracias.

**Comment by feliP-hub** [comment]
Hola saludos

**Comment by giancode1** [comment]
Hola buena charla y demostración!!

**Comment by gilbertoesp** [comment]
¿Cuál herramienta de IA generativa utilizas más? He estado usando más Bard
desde que incluyeron los chats pasados.

**Comment by AndreaGriffiths11** [comment]
Que pena con todos!!! Tenia dos streams y me confundi en cual complete el sorteo. Pero aqui esta felicidades @6erman porfavor enviame un correo a andreagriffiths11@github.com para recibir tu premio!

Mil gracias a todos por su tiempo 

<img width="901" alt="Screenshot 2023-08-10 at 2 36 05 PM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/836b1201-90db-4483-88ed-649e06e458d6">

**Comment by gilbertoesp** [comment]
Felicidades a German por ganar. Sigamos todos en el sendero de nunca para
de aprender
