### ISSUE TITLE
PyCon LATAM 2023

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#28]
## Hola, PyCon LATAM! ¡

Muchas gracias por tu tiempo el día de hoy y por ser TÚ!

<img width="325" alt="Screenshot 2023-08-25 at 12 29 23 PM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/7b0d4daa-51c9-48e8-9834-0a230155336a">

Aquí te compartimos el [enlace de recursos](https://github.com/githubpresente/pycon-LATAM-recursos) de la presentación de hoy, y no olvides unirte a nuestro [Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/pyconmx23).

🚩 Si eres un lider de una comunidad en tu universidad, recuerda que tenemos abiertas las postulaciones para GitHub Campus Experts, nuestro programa para apoyar a crecer tu comunidad. Las aplicaciones están abiertas hasta el 1 de septiembre. [¡No te pierdas la oportunidad de aplicar!  ](https://education.github.com/campus_experts)

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 **Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue** 👇

## 🏆 Premios se sortearán el 26 de agosto a la 5:30 p.m. en el stand de GitHub.

✍🏽 Un par de Términos y Condiciones:

- Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
- No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).
- El premio de la rifa no se puede cambiar o intercambiar.
- ¡El ganador del premio **DEBE estar presente** cuando saquemos un ganador, de lo contrario, volveremos a sortear!

¡Buena suerte!

**Comment by Aracely-wh** [comment]
Hola desde Monterrey!! Aracely Alamilla

**Comment by manuelmgil** [comment]
Saludos desde PyLatam Monterrey

**Comment by rogerwh** [comment]
Un gusto estar en PyconLatam Monterrey :D 🐍 
Roger Arjona

**Comment by josegarza160** [comment]
Holaaa

**Comment by capuche777** [comment]
Saludos, gran evento

**Comment by rigelvera** [comment]
Saludos desde Pycon LATAM

**Comment by Flamel05** [comment]
PyLatam 2k23!!

**Comment by datormx** [comment]
Ya en PyCon Latam en Monterrey 🤓🐍💛💙

**Comment by maye-vaca** [comment]
PyCon LATAM en Monterrey!!

**Comment by Raymundoo** [comment]
Holiwis

**Comment by BenjaStamaBel** [comment]
Saludos a PyCon Latam

**Comment by danvergara** [comment]
Salud Pylatam!!

**Comment by EdsonECM17** [comment]
Saludos

**Comment by luisjimenez6245** [comment]
Hola a todos!!!

**Comment by fitoria** [comment]
Saludos desde pylatam

**Comment by SantiagoJejen** [comment]
Hola desde Monterrey, Santiago

**Comment by lcmartinezdev** [comment]
Hey!

Desde Pycon LATAM 2023!

👀

**Comment by keivydominguez** [comment]
PyconLatam Monterrey ✌🏻🐍

**Comment by Mirelle15** [comment]
Saludos a todos!! Arre 🤠
Atte. Mirelle

**Comment by fherdlcruz** [comment]
Pyconlatam Monterrey 2023

**Comment by alflores21** [comment]
PyConLatam23 Monterrey :)

**Comment by fenixjdgo** [comment]
Que tal, feliz de estar aquí en el PyCon Latam 2023.

**Comment by DeimonRitus** [comment]
PyconLatam Monterrey 2023, Endava Latam!!

**Comment by miguelsantos-wh** [comment]
Hola PyconLatam! Un gusto estar presente aquí en Monterrey 🤠🤙Miguel Santos

**Comment by leonardo-wh** [comment]
Saludos desde PyLatam Monterrey! 🤠

**Comment by ramrodo** [comment]
Hola! Desde el EDOMEX y GDL para MTY :)

**Comment by Vrani7** [comment]
Muy bueno el evento de Pycon Latam🐍🐍🐈‍⬛

**Comment by gustavocd** [comment]
Hola PyLatam 2023 🤟🏼

**Comment by lcyepiz** [comment]
Saludos, pycom mty 2023

**Comment by Francisco-Frias** [comment]
Excelente evento y speakers gracias PyConLatam 2023!! 🐍🐍🥳

**Comment by juanpabloprado** [comment]
Saludos Vicente y Andrea soy Juan

**Comment by lorddemon** [comment]
Saludos Python Latam 2023

**Comment by alarcon7a** [comment]
Vine por el lenguaje y me quede por la comunidad

**Comment by luiscberrocal** [comment]
Saludos Python Latam 2023

**Comment by devcsar** [comment]
Hola pyconlatam, excelente ambiente 😉

**Comment by william-monroy** [comment]
:octocat: Gracias a todos los organizadores y participantes por este evento. Espero aprender mucho de ustedes ❤️

**Comment by adrian-martinez-dev** [comment]
Hola a todos PyCon, ¡Saludos!

**Comment by Biaku** [comment]
Hola Mundo, #pyconlatam

**Comment by mental12345** [comment]
Saludos Pycon Latam!!

**Comment by ghost** [comment]
Saludos desde pylatam.org 2023!

**Comment by SolDavidCloud** [comment]
Muchas gracias! Suerte a todos!

**Comment by astercraker** [comment]
Hi, i,m sunday

**Comment by 6little6fang6** [comment]
HOLA DESDE EL PYCONLATAM WUU

**Comment by cmosta0** [comment]
Hey!

**Comment by yalbibalderas** [comment]
Saludos al capítulo de PyLadies CDMX!!!

**Comment by pixelead0** [comment]
# Quiero regalitosssss!!!!!!
Suscribanse a la lista de correos de python México 
https://mail.python.org/mailman/listinfo/python-mx

**Comment by GaboGomezT** [comment]
Arriba PyCon LATAM!

**Comment by hilariosaurio** [comment]
Saludos a la PyCon LATAM un placer asistir y conocer gente tan chida 🤠
Y la carnita asada? 🔥

**Comment by Brayan244** [comment]
Hola

**Comment by astercraker** [comment]
Hi, i,m sunday

**Comment by fenixjdgo** [comment]
Buena conferencia!

**Comment by capuche777** [comment]
Seguimos en la PyCon!

**Comment by keivydominguez** [comment]
🐍💙✌🏻

**Comment by EdgarIn64** [comment]
Pycon MTY

**Comment by digicornio** [comment]
:)

**Comment by FernandoPrzGmz** [comment]
Pylatam2023 👀

**Comment by holasoymalva** [comment]
Hola, jeje larga vida a la Jaiba Brava!!! 🦀

**Comment by JesusLoera** [comment]
Hola gente de PyCon Latam 2023

**Comment by holasoymalva** [comment]
la Js Conf es el mejor evento del mundo 
![image](https://github.com/githubpresente/selector-rifa/assets/13058234/60cb4052-b53e-4321-a9bb-f7c0f5d1e58d)

**Comment by holasoymalva** [comment]
Lo siento error de dedo, la PyConf es el mejor evento del mundo!!

![image](https://github.com/githubpresente/selector-rifa/assets/13058234/9392109c-e95f-4ade-9d87-11254d79d228)

**Comment by Julio-WH** [comment]
Hola uwu

**Comment by MarcoGreen98** [comment]
Primera vez en el #PyconLatam ! 😄😄🥳

**Comment by JesusLoera** [comment]
Mi primera PyCon!!

**Comment by ErickdeMauleon** [comment]
En mi local sí corría ayer 🤠

**Comment by julio-reyes11** [comment]
Hola #PyLatam

**Comment by holasoymalva** [comment]
Yo al ver que la liga 'http://localhost:3000/' que le comparti al cliente no le funciono :'v 
![image](https://github.com/githubpresente/selector-rifa/assets/13058234/3082d132-d7b1-43cb-9b41-683ebc96e6f0)

**Comment by ErickdeMauleon** [comment]
Como cuando encuentro a la persona que no deja de meter bugs al proyecto de la empresa
![images (73)](https://github.com/githubpresente/selector-rifa/assets/22137108/c259b7c8-b1ea-443b-af0f-2ab851fb5815)

**Comment by AndreaGriffiths11** [comment]
Muchas gracias a todos por su participación y apoyo! Son lo máximo ♥️

No olviden unirte a nuestro grupo de meetup 

Check out GitHub [¡Presente!: En Español on Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a)

![image](https://github.com/githubpresente/selector-rifa/assets/20666190/57123ad2-a84e-4069-aa79-2b15c39e2e18)

![image](https://github.com/githubpresente/selector-rifa/assets/20666190/8e8da5ed-e082-40d5-b20d-b70483e2a877)

![image](https://github.com/githubpresente/selector-rifa/assets/20666190/38e9d5f2-0c6e-4524-affc-c500bfaec1b2)
