### ISSUE TITLE
Dia 1 - Virtual DevOpsDays Medellin

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#3]
### Para participar en este sorteo de swag solo tienes que dejar un comentario en este issue ⬇️ 

¡Únete a nuestro [Meetup en español](https://www.meetup.com/githublatam/) y sé parte de nuestra comunidad! Si deseas compartir tus conocimientos como ponente, te invitamos a enviar tu propuesta de charla a través de [este enlace](https://githubmeetup.typeform.com/to/LWlStlet). ¡Estamos emocionados por conocer tus ideas y enriquecer juntos esta experiencia! 
Buena Suerte!

**Comment by RiveroDev** [comment]
Muy buen dia .. Excelente actividad!

**Comment by jleonardod** [comment]
Buen día para todos.... Super!!!!

**Comment by JhonierCordoba** [comment]
Buenos días... Genial!!

**Comment by Mayerlymu** [comment]
Buenos días!
DevOps Day Medellin - Gran oportunidad de conocimiento y relacionamiento.

**Comment by Nina118920** [comment]
- Genial este tipo de eventos en el mundo TI!! #1

**Comment by AfiffeRetamozo** [comment]
Me encanta esta temática

**Comment by cecasta** [comment]
Genial esta charla. tks

**Comment by germanpeart** [comment]
Muy buena charla. Saludos.

**Comment by redux-edgardo-vergara** [comment]
Gracias por estos espacios! #1

**Comment by LordArshen** [comment]
Gracias por compartir el conocimiento

**Comment by crist1333** [comment]
aprendiendo, aprendiendo!! DevOpsDays Medellín 2023 !!

**Comment by Mayerlymu** [comment]
Hola!!  Somos Devco 🚀  tenemos amplia experiencia en Automatización de Pruebas, Desarrollo de Software, Evolución Cloud y Transformación DevSecOps, siendo esta una línea transversal en todo el proceso. Somos aliados de grandes compañías multinacionales en Colombia y LATAM... 
¿Estás preparado para hacer las cosas mejor que antes?  

🗣️Hablemos: negocios@devco.com.co / +57 3243568115

Visítanos:  https://www.devco.com.co/  @somosdevco

**Comment by redux-edgardo-vergara** [comment]
DevOpsDays Medellín 2023 !!

**Comment by jlr527** [comment]
Buen día, saludos.

**Comment by lvanessaM** [comment]
Mi agradecimiento al evento DevOpsDays Medellín 2023 por proporcionarnos una amplia gama de información y conocimientos de alto valor.

**Comment by afrodriguez68** [comment]
Muchas Gracias DevOpsDays Medellín 2023!!!

**Comment by Mayerlymu** [comment]
Una gran vitrina de conocimiento en TI, aportes para nuestros proyectos y relacionamiento efectivo.

**Comment by Malcak** [comment]
Gracias!

**Comment by CondePoponcio** [comment]
Muchas gracias un gran evento !!!

**Comment by yolombana** [comment]
Muchas gracias!!

**Comment by stevensgarcia** [comment]
GitHub Forever!

**Comment by xjohnyknox** [comment]
A través de la comunidad hacemos que el talento local sea de los mejores de la región.

**Comment by cabustos** [comment]
excelente dia, DEVOPS

**Comment by Stifra** [comment]
Gracias por estos espacios, saludos!

**Comment by davenisc** [comment]
Buenas tardes, excelente actividad!

**Comment by AndreaGriffiths11** [comment]
¡Felicidades @cabustos @davenisc son los ganadores!!! Por favor enviar un DM por Twitter a @ alacolombia para darte tu premio 🎁

Gracias a todos por participar!

**Comment by AndreaGriffiths11** [comment]
<img width="1053" alt="Screenshot 2023-05-19 at 8 37 16 AM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/de2e50c8-5426-42c2-9ebc-6f288649dd93">
<img width="1155" alt="Screenshot 2023-05-19 at 8 37 26 AM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/ccc8f4b8-05bb-42f3-8d62-daa478d9cd8e">

**Comment by santiagoalex** [comment]
Genial!

**Comment by santiagoalex** [comment]
Genial!

**Comment by CristhianCanar** [comment]
Vamos con toda por ese premió, agradezco mucho de estos espacios de aprendizaje para optimizar nuestro tiempo con estas herramientas tan cracks!
