### ISSUE TITLE
GitHub CDMX v7 - 2023

### ISSUE THREAD

**Issue by LucioD3v** [gittogethers/selector-rifa#30]
¡Hola!

<img src="https://github.com/githubpresente/selector-rifa/assets/6353852/7e33ce4c-3276-4fb9-adec-0b5ad89a0ba4.png" width="325" height="400" />

Primero que nada gracias por asistir a nuestro séptimo evento en las oficinas de Platzi y de verdad, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides unirte a nuestro :
- [Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).
- [Facebook Page](https://www.facebook.com/profile.php?id=100088519489810).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/pyconmx23).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán el 08 de septiembre en el evento.
✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

- El premio de la rifa no se puede cambiar o intercambiar.
- ¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!

¡Buena suerte!

**Comment by LucioD3v** [comment]
Recuerden seguir la cuenta en Instagram: 

https://www.instagram.com/githubcdmx/

**Comment by ManuOSMx** [comment]
No olviden compartirnos/ etiquetarnos en sus fotos y vídeos que suben a sus redes. Estamos felices de ver el impacto que tienen las sesiones en sus vidas. 

Ustedes hacen que éste evento sea posible. <3

**Comment by aendrch** [comment]
Saludooooos!

**Comment by jorge-jrzz** [comment]
Punto pai 🐍

**Comment by Antonio072** [comment]
Un saludo al evento de GitHub aquí en CdMx, un gusto que vuelvan los eventos mensuales

**Comment by miguelseguramx** [comment]
**Hello Wold**

[Conóceme un poco mas](https://instagram.com/miguelseguramx)

**Comment by JoseAlfredo95** [comment]
Hallo

**Comment by ItielSanzAXO** [comment]
Puro GitHub Open Source CDMX 🔥

**Comment by SolDavidCloud** [comment]
¡Suerte a todos!
![Uploading 1000013499.jpg…]()

**Comment by DiegoOLopez** [comment]
🦄

**Comment by miguelseguramx** [comment]
**Hello Wold**

[Sobre mi](https://miguelseguramx.com/)

**Comment by Maiki2002** [comment]
Holaaa 🥺🥺

**Comment by AlanHerCas** [comment]
🎰🎊

**Comment by zoearenas** [comment]
Saludooooos ✨
Gracias por la invitación 🩷👾

**Comment by IlseOlivera** [comment]
Muy feliz de estar aquí, es la primera vez que vengo ✨

**Comment by TaliPaoHH** [comment]
I love GitHub CDMX! 💚

**Comment by Axopunkmx** [comment]
AxoPazos Here!!

**Comment by VictorHugoChavez** [comment]
HELLO GITHUB V7

**Comment by Aeroneto** [comment]
Que emoción de venir a github

**Comment by Nery1888** [comment]
Feliz de estar en Github. ❤️

**Comment by Guadalupe2410** [comment]
Hi Github v7!!

**Comment by Carlos-Nicolas** [comment]
A b c d .... a b c d .... a b c d

**Comment by AlejandroCuestaR** [comment]
Holaa, saludos.👀

**Comment by LucioD3v** [comment]
> .

No cuenta...

**Comment by saulrodriguezsk** [comment]
Siiiii GitHub es lo máximo!!!!

**Comment by Leviakc** [comment]
Importante sus reuniones

**Comment by cristhianmt** [comment]
Al millon Github

**Comment by andreavillavicencio28** [comment]
Hi, llegué tarde jejeje

**Comment by Churi35** [comment]
Bastante entretenido

**Comment by angelmz88** [comment]
Hola mundo

**Comment by TristanDom** [comment]
Github <3
