### ISSUE TITLE
70 Aniv FCFM (UANL)

### ISSUE THREAD

**Issue by LucioD3v** [gittogethers/selector-rifa#36]
¡Hola!

<img src="https://github.com/githubpresente/selector-rifa/assets/6353852/f99bc6cc-a511-47f6-9c86-c22bd733abab).png" width="300" height="350" />

Primero que nada gracias por asistir a la conferencia impartida por nuestro GitHub Leader Vicente Guzmán, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides unirte a nuestro :

[Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).
[Facebook Page](https://www.facebook.com/profile.php?id=100088519489810).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/pyconmx23).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán el 18 de septiembre en el evento.
✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.

¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!

¡Buena suerte!

**Comment by LucioD3v** [comment]
Prueba 01

**Comment by diegodaac** [comment]
Holi 🥸

**Comment by trobledo01** [comment]
Holo 👋

**Comment by Ruben421** [comment]
hola 🔥🔥

**Comment by JorgeLu03** [comment]
:)

**Comment by raulgg764-edu** [comment]
Holaa

**Comment by JulioElPapasUANL** [comment]
Saludos @julioelpapas en Instagram y demás redes

**Comment by trobledo01** [comment]
Holo 👋

**Comment by mazerman03** [comment]
Hola :)

**Comment by AntonioCV09** [comment]
Hola 🧑🏻‍💻

**Comment by aldoht** [comment]
ola :)

**Comment by vsan193** [comment]
:))

**Comment by Eliezer03-dotcom** [comment]
Hola 😀

**Comment by Carlos56g** [comment]
Puro Tamaulipas, y flautas de harina

**Comment by RobertoGarza171198** [comment]
Hola

**Comment by Exatoon27** [comment]
Hola 👋🏼, muy buena la conferencia 💯

**Comment by mariobeal** [comment]
Holi :3

**Comment by MelySanchettz** [comment]
Hola 🫰

**Comment by Escreit** [comment]
Wenas tardesss un saludooo

**Comment by Torchiz** [comment]
Un saludito chida conferencia 😍👍

**Comment by esmeygatito** [comment]
Holii 😺😺 gracias por la Conferencia

**Comment by diegoalanis1** [comment]
hola

**Comment by charlieyvelage** [comment]
Hola a todos

**Comment by AFLeonardo** [comment]
Puro Windows 7💪

**Comment by ErickMTzRdzXD** [comment]
ඞ Hola ඞ

**Comment by J-Cazz** [comment]
:3

**Comment by OscarVenegas** [comment]
Linux

**Comment by ValeriaNaige** [comment]
Holi:)

**Comment by rebecajc** [comment]
Hola:)

**Comment by MarioAR6** [comment]
Hola🦬🦬

**Comment by monycolors** [comment]
Holaaa

**Comment by OliverRiemann** [comment]
Buena conferencia!!!

**Comment by yepo-1** [comment]
Holaa🦬

**Comment by Roselove12** [comment]
Increíble persona

**Comment by LuisaSabanero** [comment]
Holaa c:

**Comment by MiguelVazquez2003** [comment]
🙌

**Comment by EduardoOso07** [comment]
Hola
