### ISSUE TITLE
.NET Dominicana Meetup

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#38]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/1c95183f-b354-4485-b500-04c158e7f450)

Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides unirte a nuestro:

[Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/pyconmx23).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán el 04 de Octubre en el evento.
✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by lesterbotello** [comment]
Hello!

**Comment by nminaya** [comment]
✌🏽

**Comment by marcoslora** [comment]
🙌🏻

**Comment by CarlosD-13** [comment]
🔥

**Comment by GiancarloAlvarez** [comment]
Hello

**Comment by Nelsonsoto22** [comment]
🫡

**Comment by ReinisEspinal** [comment]
👀

**Comment by off1n3** [comment]
🔥💪🏽

**Comment by servikore** [comment]
👋

**Comment by jamercedes** [comment]
Disfrutando la charla con la misma emoción de la primera vez.

Enjoying the talk with the same excitement as the first time

**Comment by maykoestevez** [comment]
Gracia por compartí!

**Comment by StormShadonw** [comment]
Yo quiero mi premio

**Comment by Gualo24** [comment]
hola

**Comment by nicobv01** [comment]
👋

**Comment by wmancera** [comment]
Tamo ready

**Comment by Michael-Nunez** [comment]
Present!

**Comment by EmilSor17** [comment]
🍀

**Comment by juniorfelixgb** [comment]
Hi 👋

**Comment by AbelRodriguezSolano** [comment]
☕

**Comment by j3delossantos** [comment]
Hello!

**Comment by mfxgarcia** [comment]
🫵🏽

**Comment by Starlk** [comment]
Hola

**Comment by juniorfelixgb** [comment]
Hello
