### ISSUE TITLE
GDG Dev Fest SDQ 2023 - Getting Started with DevSecOps

### ISSUE THREAD

**Issue by luispujols** [gittogethers/selector-rifa#39]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/1c95183f-b354-4485-b500-04c158e7f450)

Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides unirte a nuestro:

[Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/pyconmx23).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán el 06 de Octubre en el evento.
✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by rickyshark** [comment]
RLS

**Comment by dluismendezpy** [comment]
Luis Mendez

**Comment by fulviomoya** [comment]
🤓

**Comment by javiercm1410** [comment]
🐶

**Comment by David-PX** [comment]
🔥🔥🔥

**Comment by jsep** [comment]
devfest2023

**Comment by sperezm97** [comment]
Sebas

**Comment by kelvinlee0225** [comment]
DevSecOps!

**Comment by EmmaPj18** [comment]
Emmanuel Polanco e.e

**Comment by educr6** [comment]
/o/

**Comment by neryad** [comment]
🤘

**Comment by saulocarrasco** [comment]
😎

**Comment by uppy19d0** [comment]
Devfest2023

**Comment by anibalventura** [comment]
🚀

**Comment by LNagad** [comment]
Fire

**Comment by AnthonyGrullonA** [comment]
⚠️⚡

**Comment by samilr** [comment]
<Comments/>

**Comment by MoscatN** [comment]
👨🏻‍💻

**Comment by eericart** [comment]
👀

**Comment by WilsonJrDiaz** [comment]
Wilson was here!

**Comment by Freddyerf** [comment]
🔥🔥

**Comment by Lilonl** [comment]
👍😊

**Comment by yefryprz** [comment]
Dev fest2023 Daybin Perez

**Comment by Alex-GCS** [comment]
😁😁

**Comment by xStreeTWolFx** [comment]
DevFest 🐺

**Comment by abiezerm** [comment]
Presente

**Comment by David-PX** [comment]
💪

**Comment by wpadilla** [comment]
👨‍💻DevFest!

**Comment by EdisonJpp** [comment]
🧑‍💻

**Comment by Sirgogo95** [comment]
Devfest 2023 🔥

**Comment by josuemenap** [comment]
Nitido

**Comment by znzn00** [comment]
Hola desde el devfest.

**Comment by lewisdarkone** [comment]
Candela, fuego chipa y llama, quien llama?

**Comment by Mrtakatakard** [comment]
😎👌

**Comment by esantana21** [comment]
One piece

**Comment by EddyCordero** [comment]
🧑🏽‍💻

**Comment by Starlk** [comment]
Oli

**Comment by brandox02** [comment]
Brandox02

**Comment by joellgomez02** [comment]
💪

**Comment by OdalisAbreu** [comment]
🥳🥳🥳

**Comment by chronosjr** [comment]
Saludos!

**Comment by NaDisla** [comment]
#GoogleDevFest2023 💻❤️

**Comment by ismaelfranciscosantanaborges** [comment]
💻

**Comment by Ilbert130** [comment]
Devfest 2023

**Comment by angelbencosme** [comment]
🤙🏻

**Comment by Oneivi** [comment]
Hello 👋

**Comment by Alex-GCS** [comment]
💪🏽

**Comment by angel-lovee** [comment]
DevFest2023

**Comment by AlejandroDePena** [comment]
🙂

**Comment by juan336p** [comment]
😁

**Comment by Manokero** [comment]
DevFest23 💻

**Comment by itsmrlonzo** [comment]
DevSecOps Engineer!

**Comment by cpalacios2** [comment]
Carlos Palacios

**Comment by AntRed1** [comment]
Gracias Luis!!!
/

**Comment by joellgomez02** [comment]
Joellgomez02

**Comment by Michael-Nunez** [comment]
Hello!

**Comment by AlejandroDePena** [comment]
Devfest 2023 👍

**Comment by Geisonm161** [comment]
👍

**Comment by Geisonm161** [comment]
Hello

**Comment by Euripidec** [comment]
![Uploading 02d9fad3-3fad-48e1-9d2b-f613c2131b37.jpeg…]()

**Comment by JohannLH** [comment]
👍

**Comment by diazlisbeh** [comment]
`print("Holaaa")`

**Comment by melnotmiss** [comment]
yeehaw 🤠

**Comment by Galfaulara** [comment]
DevFest2023

**Comment by RjCastro0** [comment]
Google Dev Fest✨

**Comment by TineoC** [comment]
console.log("Hi i'm at Google Devfest")

**Comment by ericramirez** [comment]
Everybody wants to rule the world

**Comment by xmelan** [comment]
👩‍💻

**Comment by dcapellan** [comment]
Hello Hello!

**Comment by hatzard** [comment]
Dígito: D

**Comment by IKelar** [comment]
Here

**Comment by CarlosSantos0** [comment]
Vamos allá 💻🔐🔥🔥

**Comment by Morphi007** [comment]
🚀👨‍🚀.jS

**Comment by lapepeta** [comment]
Hola

**Comment by JustinLuuu** [comment]
la suerte está conmigo 🤩

**Comment by ambiorixl** [comment]
Excente contenido de la charla

**Comment by rafaeldj4** [comment]
🔥🔥

**Comment by DannyOzuna** [comment]
🔥

**Comment by ramonpjls** [comment]
10x Developer 😎

**Comment by Ranfit** [comment]
🏆

**Comment by Alexvil1131di** [comment]
🫂

**Comment by malquielb** [comment]
Hi!

**Comment by lapepeta** [comment]
La mejor charla

**Comment by wpadilla** [comment]
Best

**Comment by wpadilla** [comment]
Great

**Comment by wpadilla** [comment]
Devfest + github

**Comment by wpadilla** [comment]
Cool

**Comment by wpadilla** [comment]
Go
