### ISSUE TITLE
CodeCamp SDQ 2023 - Developer Experience: Helping your team and your business thrive

### ISSUE THREAD

**Issue by luispujols** [gittogethers/selector-rifa#44]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/1c95183f-b354-4485-b500-04c158e7f450)

Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides unirte a nuestro:

[Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://education.github.com/benefits?utm_source=2023-10-21-ccsqd23).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán el 21 de Octubre en el evento.
✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by Alex-GCS** [comment]
💪🏽

**Comment by TineoC** [comment]
Chris Tineo 🌴

**Comment by juniorfelixgb** [comment]
Hi, Junior Felix 👋

**Comment by Michael-Nunez** [comment]
Hello!

**Comment by ASB24** [comment]
Alex Serafini 🤌🏻

**Comment by AlephCK** [comment]
Hello!

**Comment by SrDaviid** [comment]
Hi, David Frias

**Comment by fva062001** [comment]
Fernando Valerio

**Comment by javieralessander** [comment]
Javier Montero

**Comment by fj-ramirez** [comment]
Klk ✌️ Felix Ramirez 🇩🇴

**Comment by javiercm1410** [comment]
♦️

**Comment by KemberlyMiliano** [comment]
Hi there!

**Comment by HegerAriasSantos** [comment]
Hello!

**Comment by Marizel02** [comment]
Yeiiii 🙌🏻💃🏻🥳

**Comment by psolenny** [comment]
☺️🚀

**Comment by psolenny** [comment]
Hi, Solenny Peralta

**Comment by Christopherodrz** [comment]
Cuidando tus cambios para no cambiar el proyecto.

**Comment by elvladi15** [comment]
Good morning!

**Comment by anagparedes** [comment]
Hola! 😄

**Comment by diegoberas** [comment]
hello

**Comment by en-medina** [comment]
Hi

**Comment by geodm20** [comment]
Waos

**Comment by RafaelDeve** [comment]
Wawawa Mundo

**Comment by carlose0808** [comment]
Hello World!

**Comment by hvsqz477** [comment]
Hello world

**Comment by wcastillo01** [comment]
Klk mundo 🇩🇴

**Comment by Dlperalta0805** [comment]
Hi!!! A disfrutar de este excelente evento 😍😍

**Comment by LegnarACV2** [comment]
Rangel Francisco Acevedo 👋

**Comment by alfredxp** [comment]
Luis Alfredo

**Comment by cronidas** [comment]
Félix Quevedo

**Comment by Fmanuel809** [comment]
Felix Martinez 😎

**Comment by dalvinxo** [comment]
Dalvin Molina.

**Comment by ronelpanag** [comment]
Hi, Guthub 🫶🏽

**Comment by joao010** [comment]
Hellooo!!!😼

**Comment by Coshtel** [comment]
> ![Image](https://user-images.githubusercontent.com/20666190/272581696-1c95183f-b354-4485-b500-04c158e7f450.png)
> 
> Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!
> 
> No olvides unirte a nuestro:
> 
> [Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).
> 
> 👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://education.github.com/benefits?utm_source=2023-10-21-ccsqd23).
> 
> 🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.
> 
> 🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇
> 
> 🏆 Los premios se sortearán el 21 de Octubre en el evento. ✍🏽 Un par de Términos y Condiciones:
> 
> Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).
> 
> El premio de la rifa no se puede cambiar o intercambiar. ¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear! ¡Buena suerte!

Lucille por aquí!

**Comment by Kyonru** [comment]
Hello world!

**Comment by ramonpjls** [comment]
10x Developer 😎

**Comment by danielomontero** [comment]
Hi there, I'm Daniel Montero

**Comment by EnmanuelParedesR** [comment]
🐸

**Comment by noelparedes** [comment]
Active on CodeCampSDQ

**Comment by David-PX** [comment]
🔥🔥🔥

**Comment by LuisEstebanC** [comment]
Luis Capellan! ✨

**Comment by kkloin** [comment]
Kelvin Sánchez 🇩🇴

**Comment by EnriqueCO1406** [comment]
Carlos Enrique. Saludos github 🚀

**Comment by christianrd** [comment]
> ![Image](https://user-images.githubusercontent.com/20666190/272581696-1c95183f-b354-4485-b500-04c158e7f450.png)
> 
> Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!
> 
> No olvides unirte a nuestro:
> 
> [Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).
> 
> 👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://education.github.com/benefits?utm_source=2023-10-21-ccsqd23).
> 
> 🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.
> 
> 🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇
> 
> 🏆 Los premios se sortearán el 21 de Octubre en el evento. ✍🏽 Un par de Términos y Condiciones:
> 
> Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).
> 
> El premio de la rifa no se puede cambiar o intercambiar. ¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear! ¡Buena suerte!

Cristian Rodriguez 💪😎 aquí

**Comment by AbelRodriguezSolano** [comment]
Hiii!! 👨‍💻

**Comment by fgrullon** [comment]
Hello, here!

**Comment by LuisEstebanC** [comment]
Hi!

**Comment by MartinsitoBritoDiaz** [comment]
Hi everyone 🇩🇴

**Comment by samill1798rd** [comment]
Hello is me !! Gilbert Samill Rivas

**Comment by Angellewis** [comment]
Hi, Angel on this side.

**Comment by miguelliranzo** [comment]
Hi, my name is Miguel Liranzo

**Comment by perlacarrasco14** [comment]
Perla Carrasco!!

**Comment by fcastillo18** [comment]
Franklin Castillo, here at Codecamp SDQ!

**Comment by FFGuerrero** [comment]
Freddy Guerrero here!

**Comment by albertraza** [comment]
Happy to be here 🪲🪲🪲

**Comment by ReinisEspinal** [comment]
👍🔥

**Comment by lvidal** [comment]
Great Stickers!

**Comment by andypauloramirez** [comment]
Hi!! 😄

**Comment by cirilobido** [comment]
#Github 🎉

**Comment by ErickJose1215** [comment]
Erick Lantigua 👀

**Comment by Dariyank** [comment]
Dariyank Sanquintin commeted your PR: "LGTM (idk what I'm seeing)"

**Comment by mrdavid0614** [comment]
Hi!! Raymond Here

**Comment by reon150** [comment]
LGTM

**Comment by David1897** [comment]
Hello David Tavarez 😊

**Comment by LeonelHolguin** [comment]
Hi!!

**Comment by Jeremy-Polanco** [comment]
🦾🦾

**Comment by MatehElismar** [comment]
@Edu-B

**Comment by Edu-B** [comment]
@MatehElismar

**Comment by Arturoevargasf** [comment]
Here we Go!

**Comment by CarlosPujols** [comment]
🙌🏼🙌🏼🙌🏼🙌🏼

**Comment by r0nni3** [comment]
Hello CodecampSDQ‐2023!

**Comment by Freddyerf** [comment]
Heyyy🔥

**Comment by Nelsonsoto22** [comment]
🤞

**Comment by Gilbert1Rosa** [comment]
👀

**Comment by Juanospafx** [comment]
Hola 👋

**Comment by cferreirasuazo** [comment]
print("I'm Cristhian Ferreira" )

**Comment by aagn2807** [comment]
Let's go 🔥

**Comment by pedrormiguel** [comment]
Here we are 💪🏾💪🏾

**Comment by JuanReneSoler** [comment]
Activo en el codecamp 2033

**Comment by christianrd** [comment]
> ![Image](https://user-images.githubusercontent.com/20666190/272581696-1c95183f-b354-4485-b500-04c158e7f450.png)
> 
> Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!
> 
> No olvides unirte a nuestro:
> 
> [Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).
> 
> 👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://education.github.com/benefits?utm_source=2023-10-21-ccsqd23).
> 
> 🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.
> 
> 🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇
> 
> 🏆 Los premios se sortearán el 21 de Octubre en el evento. ✍🏽 Un par de Términos y Condiciones:
> 
> Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).
> 
> El premio de la rifa no se puede cambiar o intercambiar. ¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear! ¡Buena suerte!

Hi!

**Comment by evaldez89** [comment]
Greetings 👍

**Comment by Srestituyo** [comment]
👾

**Comment by Zerquix18** [comment]
❤️

**Comment by ninjacksnake** [comment]
Hello world!

**Comment by enmanuel97** [comment]
Hi

**Comment by FredPeal** [comment]
Hi

**Comment by ivansanchez006** [comment]
Great 👍👍

**Comment by ericksaga** [comment]
Hi

**Comment by Sebaspena00** [comment]
Let’s go OctoGatos

**Comment by ReinisEspinal** [comment]
👍🔥

**Comment by javiercm1410** [comment]
F

**Comment by AlephCK** [comment]
Heyy

**Comment by carlose0808** [comment]
Klk world!

**Comment by jesusdstn** [comment]
💪🏻

**Comment by Saxter119** [comment]
Por acá!!

**Comment by Angellewis** [comment]
Angel Del Rosario

**Comment by Saxter119** [comment]
Tamo’ activo papi

**Comment by AngelSBM** [comment]
Hello world, from San Juan 🧙‍♀️🧙‍♀️

**Comment by MartinsitoBritoDiaz** [comment]
🇩🇴🇩🇴

**Comment by miguelliranzo** [comment]
Hi, my name is Miguel Liranzo

**Comment by nromero125** [comment]
Hi, i'm Nelson the winner

**Comment by ghost** [comment]
Hello, Emmanuel Portes!

**Comment by DeFreitas-Samuel** [comment]
Hello !! I am samuel, nice to meet y’all 🇻🇪

**Comment by miguelliranzo** [comment]
🇩🇴 Miguel Antonio Liranzo

**Comment by reynni123** [comment]
Hi!!

**Comment by Lorey417** [comment]
Hi, Jandra Jiménez here ✨

**Comment by maykoestevez** [comment]
Hi!

**Comment by castilloss** [comment]
Codecamp

**Comment by maykoestevez** [comment]
Hey!

**Comment by limarifigueroa** [comment]
Hi!

**Comment by fva062001** [comment]
HEYYY YOOOO

**Comment by TineoC** [comment]
console.log(“klk”)

**Comment by GiameFajardo** [comment]
🚀

**Comment by AlephCK** [comment]
Hello there!

**Comment by David-PX** [comment]
Ufff 🔥🔥

**Comment by d-feliz** [comment]
🚀🚀🚀

**Comment by psolenny** [comment]
Nice

**Comment by LuisEstebanC** [comment]
🐈‍⬛🚀

**Comment by Alex-GCS** [comment]
Klk

**Comment by Jpeynado** [comment]
Hello world !!

**Comment by milo0606** [comment]
🤟🏽

**Comment by alvaroben** [comment]
Hi 💪

**Comment by Leidyglez** [comment]
🚀

**Comment by AlexRojas14** [comment]
🔥🔥

**Comment by rafaeljiron** [comment]
Hi, Rafael Jiron
