### ISSUE TITLE
GitHub en EKOPARTY 2023 Raffle Dia 1 (Noviembre 1, 2023 4:30pm)

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#45]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/7c523af1-9dee-4a3f-ac68-12643e1e5db6)

![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/626e5197-825a-4502-b95b-a837e0642f7e)

Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides unirte a nuestro:

[Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://education.github.com/benefits?utm_source=2023-10-21-ccsqd23).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán después de la charla el 1 de noviembre.

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by fhielpos** [comment]
:octocat:

**Comment by Otelib** [comment]
☺️

**Comment by leyluchy** [comment]
Github tiene uno de los mejores stands de la Eko!

**Comment by Dianakts95** [comment]
Github el mejor stand de la Eko con stickers increíbles!

**Comment by Larryjose** [comment]
¡GitHub está en la Eko y es el mejor stand!

**Comment by brunoxcode** [comment]
hack the planet!

**Comment by Parasimpaticki** [comment]
👾

**Comment by charlystone23** [comment]
William y René are the best and very nice people 😊

**Comment by LCmollly** [comment]
Me lleve el ultimo sticker :p

**Comment by avozella** [comment]
Eko!

**Comment by lTato** [comment]
Que bueno está el stand de GitHub en la eko!

**Comment by MauricioFIUBA** [comment]
Vamos Eko!

**Comment by Unicornpink1234** [comment]
🦄

**Comment by SpendIce** [comment]
Aguante el copilot gratis para estudiantes, me ha salvado varias veces

**Comment by horusint** [comment]
Gracias!!!

**Comment by modsiw-mona** [comment]
🐱🐱🐱

**Comment by farah-hawa** [comment]
Hola hackers! 🇦🇷

**Comment by IgnacioSuarezB** [comment]
🥳

**Comment by LautaroAg** [comment]
:octocat:

**Comment by fabfernandez** [comment]
holamundo

**Comment by lalelucero** [comment]
Alomundo

**Comment by tbehringer2** [comment]
Eko🎉

**Comment by H3rn4n5** [comment]
Whoami!

**Comment by estebanramos** [comment]
Jelouda

**Comment by speinador** [comment]
sudo

**Comment by japr1983** [comment]
👋👍

**Comment by AgusstinN97** [comment]
Eko!!

**Comment by frosimanuel** [comment]
💯

**Comment by God4n** [comment]
Gracias por el sticker! Modo EKO!

**Comment by paumduran** [comment]
Gracias por el sticker en la Eko 2023!!

**Comment by jmfustinoni** [comment]
git commit -m “eko 2023”

**Comment by lebrito** [comment]
Vamos la eko

**Comment by Bricmir** [comment]
Aguante GitHub!

**Comment by effective-waddle-e280aa15** [comment]
Recarguen stickers que ya se los robaron a todos jaja

**Comment by DetectivesSchool** [comment]
😊👍

**Comment by 0xSkla3** [comment]
git add .
git commit -m "venga ese iPad"
git push

**Comment by imanolmarin** [comment]
Eko!! 👽

**Comment by RicardoIorio** [comment]
Aguante la eko!

**Comment by MaxiAndresTorres** [comment]
Vamo github vamo ekoo

**Comment by GaboLC98** [comment]
Eko 2023 😀

**Comment by nicolasdarnay** [comment]
Aguante Git!

**Comment by Coraline-github** [comment]
♾ github 4 life

**Comment by maiterm** [comment]
ekoooo

**Comment by facundoib** [comment]
✨️✨️✨️ekooooo

**Comment by luuliirome** [comment]
Dale la ekoo!!

**Comment by GerNov** [comment]
Ekoooo🫶

**Comment by manuovejas1** [comment]
Mejor stand de la eko

**Comment by ghost** [comment]
🚀🚀🚀🚀🚀

**Comment by HowardFigo** [comment]
Git

**Comment by 0p1um** [comment]
hola

**Comment by javito2003** [comment]
😎

**Comment by cberto** [comment]
❤️👩🏻‍💻

**Comment by KAAcevedo** [comment]
¡Ojalá me gane algo! Gracias por la buena onda en el stand de la Eko 💫🎉

**Comment by Otelib** [comment]
Excelente la charla de copilot

**Comment by BBerastegui** [comment]
Swag?!

Here I am!

**Comment by andresriancho** [comment]
😀👏

**Comment by dnpeinador** [comment]
😎💻

**Comment by NahuelGiliberto** [comment]
Vamos GH! Muy buena charla en la eko

**Comment by VexxAl** [comment]
🧉🧉

**Comment by pudidesurage** [comment]
😁

**Comment by GianSM06** [comment]
Excelente charla! Lleno de ganas de probar GH copilot!!

**Comment by FacundoZS** [comment]
💪💪💪

**Comment by Intotheunknown** [comment]
Muy buen stand y muy buena la charla de Seguridad con Copilot

**Comment by AMontesG** [comment]
Ekoparty

**Comment by jackkfrost** [comment]
Hola Eko2023

**Comment by soy-elmago** [comment]
🍀❤️

**Comment by iampuky** [comment]
🎉

**Comment by vickyBermudez** [comment]
Ekoparty

**Comment by sebadejesus** [comment]
Hack the planet!!

**Comment by FrancoPellitta2002** [comment]
Muy bueno el stand

**Comment by vcarulla** [comment]
Buenisima la chaela!! 😊

**Comment by hskodama** [comment]
Ekoparty!

**Comment by MurrayHK** [comment]
Holaaaaa

**Comment by ivanaBenitez** [comment]
Gran charla!

**Comment by cseoane-21** [comment]
Eko!!🫶

**Comment by luciaromeroML** [comment]
Go github!

**Comment by Nacho052** [comment]
holaaa

**Comment by AndreaGriffiths11** [comment]
¡Felicidades a todos los ganadores! Nos vemos mañana para mas premio y nuestra Trivia challenge a las 16:30!

![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/ee23800a-41ed-4c74-acd3-6be912e7a00c)
