### ISSUE TITLE
GitHub en EKOPARTY 2023 Trivia Dia 2 (Noviembre 2, 2023 16:30pm)

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#46]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/3d51979b-effd-4f66-91b3-ff4d6cc61760)

![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/46b1ad71-f1ce-4baf-be2e-ed55c0b56f6e)

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se otorgarán de la siguiente manera: tres ganadores serán seleccionados por acumulación de puntos en la trivia general, el premio mayor y dos finalistas. Y escogeremos dos otros ganadores usando nuestra app y serán seleccionados de entre los participantes de este issue.

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa y la actividad de Trivia NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

**El premio de la rifa no se puede cambiar o intercambiar.¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!**

¡Buena suerte!

**Comment by martinbydefault** [comment]
Hi GitHub at ekoparty!

**Comment by galoget** [comment]
Hi GitHub!

Greetings from #Ekoparty!

**Comment by mving** [comment]
💕

**Comment by farah-hawa** [comment]
I love the GitHub team ☺️

**Comment by Parasimpaticki** [comment]
🐙

**Comment by cberto** [comment]
💪🏻

**Comment by gutytox** [comment]
✊

**Comment by animesh2049** [comment]
Hola #ekoparty

**Comment by leyluchy** [comment]
Quien no quiere un peluche de octocat para el living?

**Comment by gerardosabetta** [comment]
hi

**Comment by ivaldivieso** [comment]
Github!

**Comment by horusint** [comment]
Gracias!!!

**Comment by Sebaatd** [comment]
GitHub is life!

**Comment by mateoiba30** [comment]
muy buen evento

**Comment by gbertolani** [comment]
Github!!!

**Comment by Lucia-Barcenas** [comment]
hiii❤️

**Comment by MaximoYampa** [comment]
I like git hub , good experenci git hub

**Comment by HRNN99** [comment]
:D eko

**Comment by Lucia-Barcenas** [comment]
quiero un regalo😭

**Comment by mateoiba30** [comment]
😁

**Comment by gastondeganis** [comment]
🐱🐙🖤💜

**Comment by HowardFigo** [comment]
🤝🏻

**Comment by HowardFigo** [comment]
🤝🏻

**Comment by mateoiba30** [comment]
💥

**Comment by cberto** [comment]
😁 vamoo Github

**Comment by Lucia-Barcenas** [comment]
eko party💥

**Comment by lootarola** [comment]
Github Copilot lo más grande!!

**Comment by alealbonico** [comment]
slayyy eko ✨

**Comment by gbertolani** [comment]
🥳✨✨ github

**Comment by AradiaEtreshka** [comment]
Hi!!! 🤗

**Comment by mateoiba30** [comment]
😁

**Comment by anthonyestradarojas** [comment]
Muchas gracias

**Comment by mateoiba30** [comment]
😁

**Comment by D4rkDr4gon** [comment]
Hi!! Fabulous spot and and thanks for making pur lives easier

**Comment by Lucia-Barcenas** [comment]
❤️

**Comment by MurrayHK** [comment]
Hello!!!

**Comment by gabrieltorrealba** [comment]
😉

**Comment by anthonyestradarojas** [comment]
Lo mejor de ekoparty

**Comment by Lucia-Barcenas** [comment]
🤪

**Comment by mateoiba30** [comment]
😁

**Comment by mateoiba30** [comment]
😁

**Comment by Lucia-Barcenas** [comment]
🤩

**Comment by andycreed0x** [comment]
Genial!

**Comment by GianSM06** [comment]
The best stand 🏆🏆

**Comment by Lucia-Barcenas** [comment]
the best

**Comment by anthonyestradarojas** [comment]
😃😘😘😘😘 lo mejor 
Hello

**Comment by Lucia-Barcenas** [comment]
the best stand

**Comment by Psychedelic-corpse** [comment]
👀😬

**Comment by mijalsilvera** [comment]
Ekoparty I Love you

**Comment by pirate2king** [comment]
Weeenaaa cabros!!!🇨🇱

**Comment by Lucia-Barcenas** [comment]
i love github

**Comment by IsmaelSilva0** [comment]
Hola, quiero un buzo

**Comment by mateoiba30** [comment]
😁

**Comment by Lucia-Barcenas** [comment]
quiero un regalooo

**Comment by IsmaelSilva0** [comment]
Hola, me gusta mucho github

**Comment by Lucia-Barcenas** [comment]
uso github todos los días

**Comment by IsmaelSilva0** [comment]
Hola, tengo hambre

**Comment by IsmaelSilva0** [comment]
Hola, tengo sueño

**Comment by kraken1983** [comment]
Excelente evento!

**Comment by AndreaGriffiths11** [comment]
Muchas gracias a todos por su participacion, hoy a las 12:30 tendremos mas premio, unete: [gh.io/eko23](https://gh.io/eko23)
