### ISSUE TITLE
GitHub en EKOPARTY 2023 Raffle Dia 3 (Noviembre 3, 2023 12:30pm)

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#47]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/7fa6c865-84de-4b9c-8882-b684e60d2672)

### GitHub AWARDS

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, [abre una gratis](https://github.com/join) y agrega un comentario al final de este issue con tu post en cualquier red social usando el hash #githubeko23👇

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa y la actividad de Trivia NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!

¡Buena suerte!

**Comment by ghost** [comment]
![IMG_5910](https://github.com/githubpresente/selector-rifa/assets/140553895/96a9f9c5-3437-4469-a58a-38eadaa463c7)

**Comment by galoget** [comment]
Hi GitHub!

Greetings from #Ekoparty!

**Comment by gabrieltorrealba** [comment]
😉🥳

**Comment by pirate2king** [comment]
Wena cabros!!!🇨🇱🇨🇱

**Comment by Sebaatd** [comment]
GitHub is love

**Comment by D4rkDr4gon** [comment]
![Screenshot_20231102-170008_Instagram.jpg](https://github.com/githubpresente/selector-rifa/assets/106495109/96920c80-7313-41b5-8035-3bf0573e7adf)

Hi from Ekoparty 2023

**Comment by lucoppes** [comment]
✨✨✨

**Comment by horusint** [comment]
Acá Nuevamente desde https://twitter.com/horusint/status/1720288984624935271 

Gracias #githubeko23 !!!

![Screenshot from 2023-11-03 00-58-22](https://github.com/githubpresente/selector-rifa/assets/23113455/8061b961-a647-4b24-a847-5c0c9d408535)

**Comment by AradiaEtreshka** [comment]
https://www.threads.net/@aradia.mermaid/post/CzL1qHpuE23/?igshid=NTc4MTIwNjQ2YQ==

**Comment by gabaletru** [comment]
Cuando estás tranqui en la Ekoparty y te encontras con gato pulpo más lindo que hay

**Comment by soy-elmago** [comment]
🇦🇷👋👋👋

**Comment by cberto** [comment]
👩🏻‍💻💪🏻

**Comment by Otelib** [comment]
Excelente el stand de github en la eko

**Comment by mateoalifraco** [comment]
Muy buen stand!!

**Comment by JIArb** [comment]
🎉🎉👏

**Comment by cintainfinita** [comment]
Hacking is not a crime!

**Comment by MauricioFIUBA** [comment]
![Screenshot_20231103_110047_X.jpg](https://github.com/githubpresente/selector-rifa/assets/31808401/7b9b57ec-d53a-494c-aa43-c4ff6f8de764)

**Comment by JereSch8** [comment]
![Screenshot_20231103-111102.png](https://github.com/githubpresente/selector-rifa/assets/58143759/b2f9517e-ac10-4bd9-9088-3fcb2150a24b)

#eko2023

**Comment by AradiaEtreshka** [comment]
![Screenshot_20231102-165643~2](https://github.com/githubpresente/selector-rifa/assets/85508862/120808e7-171b-448e-b30d-5ba5c6374764)

**Comment by Hernan96HMM** [comment]
![Screenshot_2023-11-03-11-13-59-063_com.instagram.android.jpg](https://github.com/githubpresente/selector-rifa/assets/73318692/c01163e2-9b1c-4d6d-bdfa-af1438e86e1a)

#eko2023

**Comment by God4n** [comment]
Ekoparty!!

**Comment by Juamba02** [comment]
Aguante github loco

**Comment by kadorrna** [comment]
![image](https://github.com/githubpresente/selector-rifa/assets/779203/3dd56f24-a622-4774-b286-aea9c0b0c274)
Aguante github

**Comment by JoacoMazza** [comment]
Vamos github

**Comment by lucoppes** [comment]
![Uploading A24A0A20-E750-4B64-8868-8A0B8208758B.jpeg…]()🤍

#githubeko23

**Comment by lucoppes** [comment]
![6BBA5449-7831-42A1-9DF3-7A68CEDC617B](https://github.com/githubpresente/selector-rifa/assets/46791966/833af0ea-1396-4ed0-bf7d-9414dbb47d5d)

#githubeko23 🤍🤍

**Comment by Sebaatd** [comment]
El mejor stand de la Eko!
![Cargando 280311214...]

**Comment by leyluchy** [comment]
Reviviendo twitter solo para este sorteo, jejeje

https://twitter.com/leyluchy/status/1720446834760470722

![image](https://github.com/githubpresente/selector-rifa/assets/31015379/a80338ec-58a7-45fc-8447-b1364e182ba4)

**Comment by Sebaatd** [comment]
El mejor stand de la Eko!
![image](https://github.com/githubpresente/selector-rifa/assets/16218785/23efbdff-805e-4910-ae81-b70388d340f5)

**Comment by GianeLopez29** [comment]
Holaaa Github, tremendo stand tienen!! ACA ESTAMOS EN LA #49 #46 #35

**Comment by lucoppes** [comment]
![C372710C-8F7D-4725-8A3E-3A6A398A5DD6](https://github.com/githubpresente/selector-rifa/assets/46791966/c072d6d8-c6ed-47a3-8408-c2dbdb360fb1)

#githubeko23 🤍

**Comment by kraken1983** [comment]
Hola!

**Comment by yuridia123** [comment]
> Participando #GITHUBEKO23

**Comment by gabotachak** [comment]
Gracias!! Muy buen stand https://www.instagram.com/p/CzMB9_grnMM/?igshid=MzRlODBiNWFlZA==

**Comment by kraken1983** [comment]
https://twitter.com/RocasLabasalay/status/1720455457880355323?t=AYYy_QvV5irhg_IGTF1n2g&s=19

Genial el stand! #50

**Comment by AndreaGriffiths11** [comment]
https://github.com/githubpresente/selector-rifa/assets/20666190/1915f61a-2f40-4997-8e1e-936b42678154

**Comment by AndreaGriffiths11** [comment]
### No olviden pasar por el Stand a las 12:30 para el sorteo!

**Comment by Parasimpaticki** [comment]
https://instagram.com/stories/parasimpaticki/3227976797884868256?igshid=YjVjNjZkNmFjNg==

**Comment by farah-hawa** [comment]
Love GitHub plushies 😌
![Uploading 7f9ed039-6895-42b7-89b3-a889bb584728.jpeg…]()

**Comment by farah-hawa** [comment]
![7f9ed039-6895-42b7-89b3-a889bb584728](https://github.com/githubpresente/selector-rifa/assets/48671052/7c65f52a-cee1-42fd-8cdc-e676b1561c51)

**Comment by notluken** [comment]
![IMG_3602](https://github.com/githubpresente/selector-rifa/assets/74316806/34599fc0-caa5-4f9a-a0a3-0767055da44b)

**Comment by SantiNG23** [comment]
![Uploading IMG_5186.png…]()

**Comment by mercado-sc** [comment]
#githubeko23
![IMG_20231103_123024](https://github.com/githubpresente/selector-rifa/assets/149803555/721bb52c-bc0a-4e51-a1e0-aed5acc67a1c)

**Comment by AndreaGriffiths11** [comment]
Gracias por participar! Recuerda nuestra conferencia empieza la próxima semana y es completamente gratuita https://reg.githubuniverse.com/flow/github/universe23/reg/login
