### ISSUE TITLE
platzi

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#52]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/63d9f87b-5b8a-4edb-9bf8-94a22656a1af)

**Comment by ramortegui** [comment]
Hola!

**Comment by samucodesh** [comment]
Hola Andrea !

**Comment by segamboam** [comment]
Copilot la herramienta que potencia a los programadores

**Comment by Dev-Jaguar** [comment]
Quiero ganar esa rifa, para poder trabajar y hacer un pull request sin ver el curso de fret

**Comment by pooldeveloper** [comment]
Hi

**Comment by CriistianRod** [comment]
Hola!

**Comment by DonovanAC7** [comment]
Saludos.

**Comment by rkrdozo** [comment]
Hola!!!

**Comment by ubaldogs** [comment]
Hola!

**Comment by edupr** [comment]
Holo! 👋

**Comment by ramonetorres** [comment]
Hola :D

**Comment by pedrozad** [comment]
Hola!

**Comment by ghost** [comment]
Me encanta conocer muchas cosas, me gusta mucho Martes de IA

**Comment by CodeGeekR** [comment]
Genial!

**Comment by Deluxer** [comment]
Github

**Comment by FMPE** [comment]
Holi <3

**Comment by JDAB23** [comment]
Hola Andrea

**Comment by walterx19** [comment]
hola

**Comment by kwuan95** [comment]
hola esperando ganar ame el platziconf

**Comment by alejombkm** [comment]
Hello everyone!

**Comment by Noruzehn** [comment]
Martes de IA🤌🏻

**Comment by asnpr** [comment]
Hola

**Comment by 0xMar** [comment]
Hola desde #MartesDeAI

**Comment by Kettyreyes** [comment]
Hola

**Comment by javrezt** [comment]
Hola

**Comment by tomas-pucutay** [comment]
✌️

**Comment by JsMelix** [comment]
Aquí Presente Deseo Probar Copilot 👨‍💻

**Comment by Jxsalinas** [comment]
Hola Andrea

**Comment by ivanchoanb** [comment]
Saludos Andrea, Copilot es lo mejor. :)

**Comment by edwinbotia1510** [comment]
Holaa !

**Comment by MLSCIENTIST1** [comment]
Siguiendola en linkedin. literalmente siguiendola por que no me voy a perder nada jajaj// saludos.

**Comment by Naiwanda** [comment]
Holaa! Desde martes con IA /Platzi

**Comment by ivethperez** [comment]
Hola!!! :)

**Comment by ThonyLarami** [comment]
Hola desde Perú !!!

**Comment by sandrarairan** [comment]
Hola

**Comment by wirigo32** [comment]
Hola, buenas noches.

**Comment by Souskiv** [comment]
Hola!

**Comment by yanko83** [comment]
Hola!!

**Comment by munalox1235** [comment]
Hola! Participando

**Comment by Danielixa** [comment]
Quiero ganar!!

**Comment by pinfradev** [comment]
Hola!

**Comment by MaryTere279** [comment]
Hola  estoy iniciando en este mundo, saludos

**Comment by lenderlucas** [comment]
Hola, conectado a Platzi live.

**Comment by gabylinares123** [comment]
Saludos desde Martes de IA de Platzi

**Comment by MaryTere279** [comment]
Hola, estoy comenzando en este mundo

**Comment by jurteagat** [comment]
¡Hola! ¡Muchas gracias por la charla! Github es una súper plataforma.

**Comment by suarez14** [comment]
Hola Andre!

**Comment by jmcastrillonb** [comment]
Hola

**Comment by munalox1235** [comment]
holi

**Comment by CristianNorga** [comment]
Hola

**Comment by pinfradev** [comment]
Hola

**Comment by sebasmolinat** [comment]
Hola

**Comment by AndreaGriffiths11** [comment]
Gracias por tu paciencia, error humano wrong issue number en el pipeline de la accion....que pena! Felicitaciones a: @kwuan95 y @Noruzehn 
<img width="1102" alt="Screenshot 2023-12-05 at 8 36 52 PM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/adc6fd96-c656-4e0a-9d73-907e5d0becff">
<img width="987" alt="Screenshot 2023-12-05 at 8 37 00 PM" src="https://github.com/githubpresente/selector-rifa/assets/20666190/59becfda-4138-494c-b44e-8d7b1c020bc4">
