### ISSUE TITLE
Sorteo

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#55]
![Image](https://github.com/githubpresente/selector-rifa/assets/20666190/63d9f87b-5b8a-4edb-9bf8-94a22656a1af)

**Comment by alarcon7a** [comment]
Holi Andre !!!

**Comment by Jean-PRM** [comment]
Hola mas platicas así

**Comment by LuisAG937** [comment]
¡Hola a todos!

**Comment by Hermestech** [comment]
Hola, quiero participar.

**Comment by Jussef** [comment]
GitHub me encanta!

**Comment by nestorrig** [comment]
Hi there

**Comment by Osvaldotr07** [comment]
Hello world!

**Comment by esalvadorlopez** [comment]
Buenas noches.

**Comment by Max23Esau** [comment]
Hola Platzinautas!

**Comment by GermanRiosGD** [comment]
Hola desde platzi, soy desarrolador android

**Comment by latqfly** [comment]
✨️👏😎

**Comment by DrRod7** [comment]
Hola, hola Andrea.

**Comment by rockzt** [comment]
Hello there!!!

**Comment by byronfba** [comment]
Hola! ✌️

**Comment by LJohnCV** [comment]
Hola excelente presentación, soy Luis caballero

**Comment by lasr21** [comment]
Hola hola

**Comment by adandgrp** [comment]
Hola, 👋 excelente charla.

**Comment by angelinaqui** [comment]
Hola

**Comment by Interactoma** [comment]
Buenas a todos 🎄

**Comment by latqfly** [comment]
Salu3

**Comment by R0BDY** [comment]
Excelente día 😊 yo también quiero participar

**Comment by SelMartinez** [comment]
Hooola! Me da mucho gusto conocerte! 🙋🏻‍♀️

**Comment by Juan-M-Cortez** [comment]
Hola, soy desarrollador y estoy emocionado por el evento de hoy. 😁

**Comment by BrendaEMtz92** [comment]
Hola, yo también quiero participar 😃

**Comment by landoledesma** [comment]
Hola que tengo que hacer?

**Comment by datormx** [comment]
Hello, GitHub presente en Platzi! 🤗

**Comment by CosmosRH21** [comment]
Hola , buena charla

**Comment by DanielCornelio** [comment]
Hola!! Más eventos así..

**Comment by conejodan** [comment]
Hola, excelente charla😁😁

**Comment by eduardosandov** [comment]
Hi. Excelent. 💚

**Comment by JoseAlfredo95** [comment]
👍

**Comment by OrozcoAntonio** [comment]
Here

**Comment by captaindrokky** [comment]
Hola todos 🦖

**Comment by Vikyalma** [comment]
👋 Hola

**Comment by Mutandome** [comment]
Hola, quiero saber cómo usarlo en un emprendimiento por fa

**Comment by Yotecatl** [comment]
Hola buena noche 🙂

**Comment by mendibox** [comment]
El selector funciona. Yo gané!

**Comment by CesarGiovani** [comment]
Hola a todos 🫡🚀

**Comment by ideyvid** [comment]
Holo a todos! Excelente exponente!

**Comment by franciscojesusmx** [comment]
Vamos por el premio!

**Comment by gscortez** [comment]
Espero no llegar tarde. Gran presentación!

**Comment by antiik92** [comment]
Hi. 😄

**Comment by Mutandome** [comment]
Chicxs si alguien se interesa en esta vacante, contáctenme por fa 

Hola buen viernes 
Por si saben de alguien que le interese la vacante 
Auxiliar de producto
Ayudar en la planificación, seguimiento y gestión de proyectos de desarrollo de productos tecnológicos.​
Trabajar de cerca con el equipo de nuestro proveedor tecnológico y diseño para asegurar que los requisitos del producto se entiendan y se implementen correctamente.​
Ayudar en la recopilación y análisis de requisitos de los usuarios y del negocio para guiar el desarrollo del producto.​
Colaborar en la organización de pruebas de producto para asegurar que los productos cumplen con los estándares de calidad y con los requisitos del usuario.​
Preparar documentación técnica, informes de progreso y otros documentos relacionados con el desarrollo del producto.​
Actuar como un enlace entre el equipo de producto y otros departamentos, como ventas, marketing y soporte al cliente.​
100% presencial, posible hibrido.
Polanco
$10,000 Bruto
Enviar CV sgarcia@alquimiapay.com

**Comment by Vikyalma** [comment]
Hola, todavía no me llega la licencia que gane. En espera de tus comentarios.   Saludos.

**Comment by AndreaGriffiths11** [comment]
@Vikyalma mira tu correo, una invitación a esta organización debe estar ahí. <Mil gracias!
