### ISSUE TITLE
Impact the Future

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#60]
![Image](https://github.com/gittogethers/selector-rifa/assets/20666190/c4f43125-85be-4b5b-8e51-357f56a4535f)

Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides unirte a nuestro:[ Meetup](https://meetu.ps/c/4FVdP/hV2Nj/a).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/pyconmx23).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán el 14 de Marzo, resultado sera publicado como un comentario en esta issue.

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar. ¡Buena suerte!

**Comment by ManuelGil** [comment]
https://github.com/ManuelGil/

**Comment by AndreaGriffiths11** [comment]
![Image](https://github.com/gittogethers/selector-rifa/assets/20666190/dff3fd77-b4d9-4886-b1ef-5eaa48b2193a)

**Comment by ManuelGil** [comment]
![image](https://github.com/gittogethers/selector-rifa/assets/25472045/e57b1b62-642f-4a44-8e3c-29dd280a97f4)

**Comment by andresovalle8** [comment]
![perfil_github](https://github.com/gittogethers/selector-rifa/assets/55222565/f10b389e-bf46-4d71-8cfa-50aaa5deb9d4)

**Comment by wongkevinmanuel** [comment]
![image](https://github.com/gittogethers/selector-rifa/assets/17505282/30664f99-1dc0-4216-a689-c408a75cd07e)

**Comment by CharlyCastrejon** [comment]
<img width="1275" alt="Captura de pantalla 2024-03-12 a la(s) 2 42 48 p m" src="https://github.com/gittogethers/selector-rifa/assets/15150834/1e239f1f-5d88-4287-b014-ad07defa98c4">

**Comment by samucodesh** [comment]
![Screenshot_20240312-164450](https://github.com/gittogethers/selector-rifa/assets/108969323/041c00e6-3702-45ce-b5c8-a80d90854df0)

**Comment by AndreaGriffiths11** [comment]
Congratulations @samucodesh please DM @alacolombiadev or email andreagriffiths11@github.com
