### ISSUE TITLE
Nerdearla Chile, Dia 1, Jueves abril 11, 2024

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#61]
Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

No olvides seguirnos por redes en: [GitHub Community](https://www.x.com/githubcommunity).

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/edu-nerdearla).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán después del cierre dia virtual.

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by Edido** [comment]
Participando!!!

**Comment by martinezvjj** [comment]
Participando

**Comment by rampmaster** [comment]
Participando

**Comment by nocrop** [comment]
Participando 🦝🦝🦝🦝

**Comment by sGoico** [comment]
# Hola nerdar.la!

**Comment by sebazamorano** [comment]
Hola Github y nerdar.la!!!!

**Comment by josefdc** [comment]
Hola hola 🤠

**Comment by Espe0311** [comment]
Participando! 😄

**Comment by JuanPabloNSZ** [comment]
🥳 **¡¡Hola GitHub!!** 🇨🇱

**Comment by rabemo** [comment]
concursando

**Comment by 4rgs** [comment]
Participando 😸

**Comment by jmaynec** [comment]
Vamos por esos premios de nerdearla!!!!!

**Comment by diegocyberops** [comment]
Hola Hola....ya participando...vamos que se puede!!!

**Comment by maeudi** [comment]
:)

**Comment by pablo1976github** [comment]
Participando, espero poder ganar algún PIN 🥇

**Comment by keaguirre** [comment]
Participando desde nerdearla online!

**Comment by virginia-ux-ui** [comment]
Participando!!

**Comment by Tammmma** [comment]
Gracias!! Participando <3

**Comment by Phosphorus-M** [comment]
Participando!

**Comment by JanisAravena** [comment]
😄 Participando

**Comment by sergioortegadev** [comment]
⭐GitHub!🦾
🤣Copilot help me!👨🏻‍💻

**Comment by pablo1976github** [comment]
> Participando, espero poder ganar algún PIN 🥇

@AndreaGriffiths11 👀

**Comment by AndreaGriffiths11** [comment]
### ¡Hola a todos! 🙌 ¡Muchísimas gracias por participar en el sorteo virtual!
🎉 Estamos mega emocionados de verlos en vivo mañana. 😄

**Felicidades a @Tammmma y @martinezvjj por favor envíenme un correo electrónico desde el correo que tienen registrado con GitHub a andreagriffiths11@github.com.** su premio es un coupon de 100USD con enviado gratituo para que compren lo que quieran en la [tienda de GitHub](https://www.thegithubshop.com/).


<img src="https://github.com/gittogethers/selector-rifa/assets/20666190/402ef97c-1df1-47c4-a725-9896f449a09d" alt="Image1" width="300"/> <img src="https://github.com/gittogethers/selector-rifa/assets/20666190/2866d5e4-0797-4ab2-b8b3-f0c477513b0d" alt="Image2" width="300"/>

Si no tuviste la suerte de ganar hoy, no te preocupes. 😉 Si asistes al evento en el GAM, tendrás otra chance de participar en el sorteo del viernes. 🍀 ¡No te pierdas la oportunidad de llevarte alguno de nuestros premios geniales! 🎁

Para participar en el sorteo del viernes, solo tienes que dejar un comentario aquí: [entrada](https://gh.io/sorteo-viernes). 📝 Queremos saber qué te emociona más del evento y escuchar tus opiniones. 💬 Recuerda, cada comentario es una nueva oportunidad para ganar. 🤞 Así que no seas tímido y comparte con nosotros lo que piensas. ¡Valoramos mucho tu participación! 😊

Estamos trabajando duro para que el evento en el GAM sea una experiencia inolvidable. 💪 Habrá charlas inspiradoras, talleres prácticos, sesiones de networking y mucho más. ¡No te lo puedes perder! 🙌

De nuevo, gracias por ser parte de nuestra comunidad y por tu increíble apoyo. 🙏 ¡Nos vemos mañana en el GAM con las pilas cargadas y listos para pasarla genial juntos! 😎

¡Hasta pronto y mucha suerte en el sorteo del viernes! 🍀🤞

**Comment by albertPerez82336** [comment]
Participando!

**Comment by xcortes** [comment]
Hola 👋

**Comment by xcortes** [comment]
Hola, hola 👋👋

**Comment by Tammmma** [comment]
Hola :3

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: xcortes ***@***.***>
Enviado: Thursday, June 20, 2024 8:42:11 PM
Para: gittogethers/selector-rifa ***@***.***>
Cc: Tamara Adasme ***@***.***>; Mention ***@***.***>
Asunto: Re: [gittogethers/selector-rifa] Nerdearla Chile, Dia 1, Jueves abril 11, 2024 (Issue #61)


Hola, hola 👋👋
