### ISSUE TITLE
Nerdearla Chile, Dia 2, Viernes abril, 12

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#62]
Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/edu-nerdearla).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán después del cierre dia virtual.

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by pablo1976github** [comment]
Participando, ansioso de mañana estar presente en Nerdear.la y presenciar las charlas de Michael, Juan Pablo y Andrea. 🤖

**Comment by andreamendezortiz** [comment]
Participando!! Nos vemos hoy en las charlas presenciales :)

**Comment by dcaminada** [comment]
Hola, buen dia, estoy participando de Nerdearla de forma Online!

**Comment by cris7ianback** [comment]
Hola buenas Participando !! 🤙😬

**Comment by Blackmist02** [comment]
Muy ansioso, esperando las charlas uwu

**Comment by neigood** [comment]
Participando en este maravilloso  evento.

**Comment by Gortubia** [comment]
Wow. ya  en el evento. espero ganar

**Comment by vmga09** [comment]
Ok

**Comment by CrissDavid484** [comment]
Ya en el evento, espero tener suerte esta vez 🙈

**Comment by Pataparapum** [comment]
Un gusto estar presente

**Comment by vieracj** [comment]
Me presenté con ganas de un libro git hub

**Comment by GiulianaEOlmos** [comment]
Hola! Participando de la nerdearla en Chile! 🇨🇱🇨🇱

**Comment by ContardoRM** [comment]
Vamos por esa rifa

**Comment by donpelusa** [comment]
Gracias por los sticker!!!! Participandooo

**Comment by sammgajardo** [comment]
hola! :) participando 😼💖

**Comment by loonita** [comment]
Participando ❤️

**Comment by nicocontreras123** [comment]
Hola! Participando 🧑🏽‍💻

**Comment by Espe0311** [comment]
Participando 🔥

**Comment by Benjamincelis23** [comment]
Participando 👀👀👀 ojalá ganar algo interesante

**Comment by rafapc2** [comment]
Ya estoy en el GAM!! Esperando las mejores charlas Nerd!! 🚀

**Comment by adaSkribana** [comment]
Gracias por la iniciativa!

**Comment by peG0r** [comment]
A ganar a ganar, gracias GitHub!

**Comment by rdiaz1973** [comment]
Gracias por la oportunidad

**Comment by nocrop** [comment]
VAMOS MONA, TE AMO MONA HERMOSA

**Comment by Alais29** [comment]
Participando!!! 🙌💜😍

**Comment by Jak0319** [comment]
Participando en el Evento #Nerdearla en el GAM!

**Comment by ErikaM83** [comment]
Me encantó deseo ganar felicitaciones

**Comment by xNoix** [comment]
Saludos desde nerdearla

**Comment by RicardoGarridoC** [comment]
> Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!
> 
> 👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/edu-nerdearla).
> 
> 🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.
> 
> 🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇
> 
> 🏆 Los premios se sortearán después del cierre dia virtual.
> 
> ✍🏽 Un par de Términos y Condiciones:
> 
> Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).
> 
> El premio de la rifa no se puede cambiar o intercambiar. ¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear! ¡Buena suerte!

**Comment by RicardoGarridoC** [comment]
Grande GitHub!

**Comment by Chrisglock** [comment]
Participando :)

**Comment by programat3** [comment]
Participando!!

**Comment by javodevon** [comment]
Participando!

Gracias al equipo de Nerdearla y Felicitaciones 💕

**Comment by hernanPoblete** [comment]
Participando :3

**Comment by KevinCastle** [comment]
Participando!! Hermosos stickers por cierto ✨

**Comment by AlFcl** [comment]
Hola

**Comment by rampmaster** [comment]
Participando

**Comment by kriollo** [comment]
Era acá, ahora si vamos por ese premio

**Comment by rolitoxdd** [comment]
participando

**Comment by bribkn** [comment]
Mucha suerte a todos!🇨🇱

**Comment by AngelTroncoso** [comment]
Participando

**Comment by lexO-dat** [comment]
Holaaaa!

**Comment by Joberto14** [comment]
No gane el miercoles, espero ganar ahora

**Comment by njofredev** [comment]
Participando!

**Comment by electronicdeivid** [comment]
Vamos que se puedeeee, participando. Saludoos <3

**Comment by pablo1976github** [comment]
Excelente! ![IMG_20240412_114722.jpg](https://github.com/gittogethers/selector-rifa/assets/147016337/7fbcf948-fa24-41fa-8650-14b83fc51342)

**Comment by AlvaroMendezT** [comment]
Participo 😋

**Comment by Rodrigojz-cl** [comment]
Gracias por los sticker!!!!

**Comment by ceciliaGeraldo** [comment]
holi soy fan de octocat y copilot!

**Comment by lauraromero-cm** [comment]
Hola. Participando 🩷

**Comment by Ronniechile** [comment]
Copilot genial

**Comment by BAM196** [comment]
Holaa

**Comment by Andressep** [comment]
Acá participando

**Comment by mmaturan** [comment]
Aca participando !!

**Comment by heimsuwu** [comment]
Participando! 🫣

**Comment by Matias311** [comment]
Participando

**Comment by Hewrek** [comment]
Github lo más grande<3

**Comment by proxylivy** [comment]
Genial el grupo, participando despues de dar entrevistas a nombre de Gabo, junto a @BGMP e @IgnacioPalma , entretencion infinita los cabros del Stand de Github :o

**Comment by KrlitosForever** [comment]
> Genial el grupo, participando despues de dar entrevistas a nombre de Gabo, junto a @BGMP e @IgnacioPalma , entretencion infinita los cabros del Stand de Github :o

Son muy geniales tuve la oportunidad de conocerlos en Gittogether :D

**Comment by Dereemii** [comment]
Participando 😍

**Comment by SebastianFeliu** [comment]
Participando!!

**Comment by kadashy** [comment]
Wena, buen stand, igual que todos vine a participar

**Comment by bbaezdev** [comment]
Participo 🤙🏼

**Comment by zeluizr** [comment]
Participando.

**Comment by javduzen** [comment]
Participando 👀

**Comment by benja-iag** [comment]
participan2 jeje

**Comment by AngelTroncoso** [comment]
Participo

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by marcelostg** [comment]
Excelentes stickers!! Espero ganar

**Comment by juancodedev** [comment]
Éxito a todos!!

**Comment by Phosphorus-M** [comment]
Participando!

**Comment by AldoCarquin** [comment]
Participandooo!!! c:
PD: Amé los stickers disidenteeeeees <3<3<3

**Comment by jjveux** [comment]
Participando rico

**Comment by xmagcx** [comment]
haber si ganamos GL!!!!  :)

**Comment by bastianSalinas** [comment]
Participando!

**Comment by FelipeCabelloE** [comment]
Participandoo

**Comment by cristiansotorivera** [comment]
Participando!

**Comment by DannyGonzalezO** [comment]
Participando!

**Comment by dancrewzus** [comment]
Participando! 🤟🏼

**Comment by adaviladev** [comment]
Aquí participando go go go!

**Comment by Fabianko** [comment]
Holaaaaaaaa

**Comment by keaguirre** [comment]
Participando!

**Comment by xovale** [comment]
Participo !! 🤓💻

**Comment by Ellamir** [comment]
Particpando!

**Comment by githubmoore** [comment]
> Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!
> 
> 👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/edu-nerdearla).
> 
> 🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.
> 
> 🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇
> 
> 🏆 Los premios se sortearán después del cierre dia virtual.
> 
> ✍🏽 Un par de Términos y Condiciones:
> 
> Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).
> 
> El premio de la rifa no se puede cambiar o intercambiar. ¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear! ¡Buena suerte!



> Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!
> 
> 👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/edu-nerdearla).
> 
> 🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.
> 
> 🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇
> 
> 🏆 Los premios se sortearán después del cierre dia virtual.
> 
> ✍🏽 Un par de Términos y Condiciones:
> 
> Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa. No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).
> 
> El premio de la rifa no se puede cambiar o intercambiar. ¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear! ¡Buena suerte!

#NERDAR_LA @githubmoore

**Comment by githubmoore** [comment]
#NERDAR_LA @githubmoore Participando

**Comment by BFzSGXL** [comment]
Participando!!! #61

**Comment by KrlitosForever** [comment]
![image](https://github.com/gittogethers/selector-rifa/assets/7423579/59b36072-962f-4d9c-8f85-1c97f95265a4)
Los mejores!!

**Comment by pabloAvila-sys** [comment]
Hola a todxs desde temprano aca participando !!!✨️👋

**Comment by Zeromux** [comment]
Gracias por todo, buenas charlas!


Participando! 😉

**Comment by SoyIsabelMM** [comment]
Me lleve miles de sticker! Los amé ❤️ amo GitHub

**Comment by sergioazoc** [comment]
Yey!

**Comment by elquimeras** [comment]
Participando!!

**Comment by odracirdev** [comment]
¡Hola mundo!

**Comment by ale13-1** [comment]
Saludos!! Excelentes charlas!

**Comment by Kellysin** [comment]
Genial los chicos del stand! 
participando por ese peluche ✨

**Comment by Laura-VFA** [comment]
Participando!!! Hello World! 😸

**Comment by Sebastiantg** [comment]
Participando por ese peluchito! :D

**Comment by samkee10** [comment]
Participando!!

**Comment by Nef-Solutions** [comment]
HOLA!!! en NERDEARLA. Aprendiendo sobre GitHub.

**Comment by renatobaez** [comment]
Hola 👋  saludos desde Iquique gracias por la 
Comunidad NERDERLA junto a mi amigo @samkee10 que se encuentra en el auditorio del GM

**Comment by IsaakCov** [comment]
Grande GitHub!

**Comment by elEdupown** [comment]
Vamooooos

**Comment by 3mp0** [comment]
Holi!

**Comment by diegotalejandro** [comment]
Git status
Win

vamos github!!!!

**Comment by XCODE89** [comment]
Excelente evento Nerdearla... Github rules!!!!

**Comment by VangelPix** [comment]
Syntaxis error

**Comment by RipTofu** [comment]
Participando!:)

**Comment by OzzYMorgadO** [comment]
Vamossss con todo!!

**Comment by JrNacho** [comment]
Participando x Nerdearla

**Comment by nojustbenja** [comment]
Aquí en #nerdearla

**Comment by hectorerb** [comment]
Participando 💪

**Comment by AndreaGriffiths11** [comment]
¡Felicitaciones a todos nuestros ganadores! 🎉👏 Estamos muy contentos de que hayan sido parte de esta experiencia tan bacana y esperamos que gocen al máximo sus premios. 🎁😊

Sabemos que la emoción de ganar es contagiosa, y los invitamos a usar el hashtag #githubsantiago en sus publicaciones. 🐙💻 ¡Queremos inundar las redes con toda la energía de nuestra comunidad! 🎊 Si comparten sus premios en las redes sociales [@githubcommunity](https://twitter.com/home) usando el hashtag #githubsantiago, no solo estarán mostrando su chévere swag, sino que también tendrán la oportunidad de ganar más premios. 

Queremos aprovechar este momentico para agradecerles desde el fondo de nuestro corazón por tomarse el tiempo de pasar por nuestro stand y saludarnos. Nos sentimos honrados de tener una comunidad tan áspera y comprometida como ustedes. Una vez más, felicitaciones a todos los ganadores y un abrazo virtual bien para cada uno de ustedes.
