### ISSUE TITLE
Nerdearla Chile, Dia 3, Sabado abril 12, 2024

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#63]
Primero que nada gracias por asistir a nuestro evento, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

👩🏻‍🎓 Si eres estudiante, no olvides que tienes acceso al GitHub Student Developer Pack, que ofrece más de 80 herramientas, incluyendo copilot, totalmente gratis. Puedes aplicar para obtenerlo en el siguiente [enlace](https://gh.io/edu-nerdearla).

🚀 Esta pagina web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions extrae a los participantes de los comentarios de este issue.

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇

🏆 Los premios se sortearán después del cierre dia virtual.

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by andreamendezortiz** [comment]
Participando en Nerdearla y en el sorteo :)

**Comment by ZoheeDH** [comment]
Participando 😄

**Comment by albertPerez82336** [comment]
Participando!

**Comment by peG0r** [comment]
Participando!! Gracias Github

**Comment by IsaakCov** [comment]
Participandoooo

**Comment by Fabianko** [comment]
Hola 💚

**Comment by Andressep** [comment]
Participando para mañana.

**Comment by Sebastiantg** [comment]
Participando por un peluchitooo :D

**Comment by Zeromux** [comment]
Participando!!! Gracias!!! 😃

**Comment by Espe0311** [comment]
Participando 💪🏻🔥

**Comment by adrianjba5** [comment]
Participo para la rifa; para seguir aprendiendo

**Comment by rampmaster** [comment]
Participando

**Comment by chicoco0987654** [comment]
Participando 🏃

**Comment by nocrop** [comment]
Está vez si vamos con todo. Mona, te necesito en mi vida con código.

**Comment by JoaquinEscobarDev** [comment]
Participando🧑‍💻

**Comment by gahumada92** [comment]
Participando

**Comment by FelipeUrdanivia** [comment]
Participando 🐱✌

**Comment by Waldanag** [comment]
Aquiiiiii participandoooo

**Comment by donpelusa** [comment]
Participando por la tazaaaaa. Cafeeeeee ven a mii

**Comment by Soofypls45** [comment]
Partiicipandoooo !! Ame los stickers!

**Comment by SebastianRiquelmeM** [comment]
Participando 😸

**Comment by alegavotti** [comment]
Participando! 💓

**Comment by Gabot3ck** [comment]
Participando 🚀

**Comment by JSBmanD** [comment]
Participando

**Comment by NepJag** [comment]
Participandoo 🫡

**Comment by STEPHKL** [comment]
Participando 😃
UX/UI designer 🖐️

**Comment by EstefaReyesG** [comment]
Hi, gracias por los Octo Cats

**Comment by fernandosilvot** [comment]
Participando

**Comment by FreeKillSWAT** [comment]
Participando!  💻🤩

**Comment by Shacosu** [comment]
Participando 🥸

**Comment by TippedJotex** [comment]
Participando :D

**Comment by IkJeff** [comment]
Participando 🎉🥳

**Comment by Kokeaft** [comment]
Participando

**Comment by Gonzalo-Anibal** [comment]
Necesitamos un OctoCat Chileno 🇨🇱!!

**Comment by Blackmist02** [comment]
Gracias por el aprendizaje que transmiten

**Comment by nicosmico** [comment]
Participando 🫡

**Comment by OzzYskate** [comment]
Vamossss activos

**Comment by OzzYMorgadO** [comment]
Vamossss activos

**Comment by MrSeba** [comment]
Participando !!

**Comment by Manuelfrnndo** [comment]
Participando c: 🥳

**Comment by kohai-of-Javier** [comment]
Cualquier cosa xd

**Comment by skay33** [comment]
Participando!!!!

**Comment by DeiM0ss** [comment]
print("participando 🤓")

**Comment by yoeldtrujillo** [comment]
console.log(“ready to win”);

**Comment by abdulaba** [comment]
Partipsndo

**Comment by josegonzalezafex** [comment]
Participando

**Comment by abdulaba** [comment]
Participando

**Comment by JulioV93** [comment]
Participando⚡️

**Comment by Diegopyl1209** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by albertPerez82336** [comment]
Participando

**Comment by spotfreeman** [comment]
Hehehe participando

**Comment by paulinasv** [comment]
Participando con toda la fe 
EU CONFÍO!!!!

**Comment by Nacho1240** [comment]
Participando!!!

**Comment by tleonn** [comment]
wueeeeeee

**Comment by HugoosZ** [comment]
Participando 👀👀

**Comment by MartinOrellana2** [comment]
Participando💪🏻💪🏻

**Comment by Mauro90P** [comment]
Participando con lo mejor de GitHub

**Comment by Valita3661** [comment]
Participando🫡💪🏻

**Comment by josue-fourier** [comment]
Participando en el sorteo!!

**Comment by crbarrera** [comment]
participando choro

**Comment by Jhopcel** [comment]
Participooo🫂

**Comment by gierckocontrerassixbell** [comment]
Cuando el octocat chileno!

**Comment by antowii** [comment]
Participando ando 🥹

**Comment by proxylivy** [comment]
Otra vez probando suerte ^^

**Comment by voishimk** [comment]
Participoo uwuu

**Comment by njofredev** [comment]
Participando!

**Comment by maxiignaciio** [comment]
Participando

**Comment by sara-tustra** [comment]
GitHub lo mejor 🤍

**Comment by NachoJuanDev** [comment]
Aguante Github!

**Comment by DarioRoman01** [comment]
Participo xd

**Comment by jaromero6** [comment]
Participo!!

**Comment by VicDario** [comment]
Participando 😄

**Comment by shannon-benavides** [comment]
Participando ando

**Comment by VicenteOstornol** [comment]
Participando, que lindo ver q github en persona, son reales!!

**Comment by ErnestoSantiago23** [comment]
Participando!!!

**Comment by barguti** [comment]
a ver que sale 😁👍

**Comment by JulioAmestica** [comment]
Participando x el libro

**Comment by aleunfor** [comment]
Ojala ganar ! Te amo Moure!

**Comment by AleizerJaneth** [comment]
Es lo mejor, se puede buscar códigos para mejorar nuestros proyectos

**Comment by nestorraulcgomez** [comment]
Participando 🤝

**Comment by framunoz** [comment]
Participando 😎

**Comment by oliverfierro77** [comment]
Participando ando!!

**Comment by EstefaReyesG** [comment]
git commit -m 'ADD: Excelente, participando'
git push

**Comment by ramirezgabrielap** [comment]
Acá estamos para Nerdearla <3

**Comment by JrNacho** [comment]
Grande GitHub en Nerdearla 2024🔥

**Comment by sebaaaz** [comment]
Participoooo 🙌

**Comment by cagodoy** [comment]
Participando 🚀

**Comment by pablo1976github** [comment]
Github lo mejor.. acá presente

**Comment by nicolasmontenegro** [comment]
Presente en Nerdearla CL 24! 👍

**Comment by AlvaroMendezT** [comment]
Participando 🤭

**Comment by ghost** [comment]
Hola 👋 Participando !!

**Comment by BFzSGXL** [comment]
Buenas acá día #2 participando de nuevo     #nerdearlachile !!

**Comment by diego12o** [comment]
Aquí participando 😄

**Comment by Shure1** [comment]
Hola!!🙋 participando :)

**Comment by SilvanaVitali** [comment]
Participando!✨️

**Comment by martincitouU** [comment]
Participanding 😇😇

**Comment by Pazstack** [comment]
Participando 😇

**Comment by jorgeriosg** [comment]
Participando

**Comment by adaviladev** [comment]
Aquí participando!

**Comment by wiseflame16** [comment]
Participando!

**Comment by SigridMV** [comment]
Hola hola, participando 
Muchas gracias

**Comment by optic4l** [comment]
Que nos vaiga bien🙌✂️

**Comment by Fabi-daza** [comment]
Participando 💪

**Comment by ElTioWise** [comment]
Participando!!!

**Comment by kriollo** [comment]
Necesito ese libro!!!

**Comment by juancodedev** [comment]
El evento está increíble

**Comment by peG0r** [comment]
Participando!! 🙌🏻

**Comment by Joaqth** [comment]
Participando 🙌👌

**Comment by JosyMaBe** [comment]
Participando 🤓🤓

**Comment by DAVstudy** [comment]
Participando

**Comment by carosartorio** [comment]
Vamos 🤗

**Comment by adaSkribana** [comment]
Github la lleva

**Comment by RipTofu** [comment]
Participando :)

**Comment by horizonxt** [comment]
Vamos 😎

**Comment by keaguirre** [comment]
Participando!

**Comment by Dereemii** [comment]
Participando 💛

**Comment by Jhopcel** [comment]
participando 😘

**Comment by 787107847** [comment]
Con todo si no paque 💪

**Comment by lorena-infante** [comment]
PARTICIPANDO!! 🎉

**Comment by PatricioDU** [comment]
Gran evento participando!

**Comment by nocrop** [comment]
Está vez si vamos con todo. Mona, te necesito en mi vida con código.

**Comment by rampmaster** [comment]
Aquí estoy

**Comment by marcelostg** [comment]
Vamos que se gana

**Comment by estebanburgoa** [comment]
Participando!

**Comment by cdnexx** [comment]
Participandoooo 🛐🛐😈

**Comment by Nicolas-Tolosa** [comment]
A cruzar los dedos 🤞🏼🍀

**Comment by JuanPabloNSZ** [comment]
Hola 👋

**Comment by asukarrr** [comment]
Participandexx 🐁

**Comment by Andressep** [comment]
Participando ando

**Comment by armikhael** [comment]
Hello Carlos participando

**Comment by vngerus** [comment]
Here we gooo

**Comment by wachunei** [comment]
hi 👋

**Comment by claudios1980** [comment]
Participando 👏👏👏👏

**Comment by ZebbasArias** [comment]
participando

**Comment by SebasIMM** [comment]
Participando!!

**Comment by Kioys** [comment]
Holaaaaa saludoss

**Comment by arausseop** [comment]
Participando

**Comment by mmogaP** [comment]
Participando

**Comment by alejurian** [comment]
Participando

**Comment by christian-aguilar1** [comment]
participandoo

**Comment by luisjup2cap** [comment]
participandoo

**Comment by cypictronic05** [comment]
Participando! por acá "Cypictronic Electrónica y Programación en tus manos" en YT.

**Comment by VixoPlank** [comment]
Ojalá ganar 💪🏻

**Comment by VixoPlank** [comment]
Participando 🍀

**Comment by cddm-gh** [comment]
Vamos con toda #nerdearla 🚀

**Comment by bastian-millanir** [comment]
Participando!!!

**Comment by Damm2222** [comment]
Participando

**Comment by GortariDev** [comment]
Participando.git

**Comment by gaenroca** [comment]
Gracias por la oportunidad de participar

**Comment by hectorerb** [comment]
#nerdearla ⚡️

**Comment by sebacassone** [comment]
aquí estoy

**Comment by JulioV93** [comment]
Participando

**Comment by leocerna1983** [comment]
Participando

**Comment by Tobarrientos2** [comment]
Participanding

**Comment by Ewglmp** [comment]
Participando en el evento

**Comment by pisaacode** [comment]
Participando 🤘

**Comment by DAHLNOV** [comment]
Participando

**Comment by alexberrios** [comment]
Participando

**Comment by angulodev** [comment]
Participando

**Comment by crxsx0** [comment]
Participo

**Comment by CILT** [comment]
Participando :D

**Comment by salazarxs** [comment]
participandooo🖤

**Comment by FranciscoCornejo** [comment]
Participando ⚡

**Comment by rllullt** [comment]
Participando!

**Comment by tomasild** [comment]
Participandoo 
Tuki!

**Comment by cristiancorreau** [comment]
Participando 🤓

**Comment by sergioazoc** [comment]
Yey!

**Comment by sergioazoc** [comment]
Vamos con todo 🙌

**Comment by Fabianko** [comment]
Holaaaa

**Comment by Fabianko** [comment]
Aquí estoy

**Comment by bastianSalinas** [comment]
Participando!!

**Comment by nedilio** [comment]
Hola desde nerdearla

**Comment by armikhael** [comment]
Quiero el peluche 😵‍💫

**Comment by hackwish** [comment]
Hola mundo

**Comment by Galit21** [comment]
Hack the world

**Comment by sergioazoc** [comment]
Wii

**Comment by sergioazoc** [comment]
😁

**Comment by jpstorm21** [comment]
Necesito un peluche para compilar mi código

**Comment by armikhael** [comment]
Hola GitHub 🤩✌️

**Comment by sergioazoc** [comment]
💚

**Comment by DevJoseAle** [comment]
Participando!€

**Comment by orianasanabria** [comment]
Participando 🚀🚀🚀🚀🚀🚀🚀

**Comment by DevJoseAle** [comment]
Participando!!!

**Comment by orianasanabria** [comment]
🖖🏼🖖🏼🖖🏼🖖🏼🖖🏼

**Comment by armikhael** [comment]
Está mala la fecha es sábado 13 🤣

**Comment by liliamadrid** [comment]
Participando!

**Comment by ablancoa** [comment]
Participando!!!!

**Comment by Ripza** [comment]
Participando!

**Comment by KattaMP** [comment]
Participando 🥸

**Comment by armikhael** [comment]
Yo quiero el peluche

**Comment by PatriciaPerezF** [comment]
Participando!!

**Comment by EstefaReyesG** [comment]
Yooooo participando

**Comment by maxoo7** [comment]
Acá participando al fin! :)

**Comment by catalinadelos** [comment]
Hola también quiero 😌!!!

**Comment by orial021** [comment]
estoy dentro de la rifa!!!
