### ISSUE TITLE
Open Source Viernes con Ulises Gascon y Express.js sorteo

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#71]
Primero que nada gracias por asistir a nuestro evento, apoyar open-source, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

![ulises ](https://github.com/gittogethers/selector-rifa/assets/20666190/2e35834e-23b8-407d-a0ac-758e52569dab)
🚀 Esta página web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions obtiene a los participantes de los comentarios en este issue.

🎫 Para participar en el sorteo, inicia sesión en tu cuenta de GitHub. ¿No tienes una? ¡No hay problema! Abre una cuenta gratis y agrega un comentario al final de este issue 👇. No es necesario crear una nueva discusión, simplemente deja un comentario aquí.

🏆 Los premios se sortearán al finalizar la transmisión.

✍🏽 Algunos Términos y Condiciones:

- Participar en este sorteo NO implica tu consentimiento para ser contactado por ningún otro motivo.
- No te agregaremos a nuestra base de datos de marketing (pero si deseas suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/)).
- El premio del sorteo no es transferible ni intercambiable.
- El ganador del premio DEBE enviar un correo electrónico a andreagriffiths11@github.com con su nombre y dirección de correo electrónico.

¡Mucha suerte!

**Comment by Fabianko** [comment]
🥇 Primer lugar!

**Comment by asyncr** [comment]
Increíble evento, saludos desde MX  ✨

**Comment by CharlyCastrejon** [comment]
¡Suerte a todos! ✨

**Comment by ghost** [comment]
Hola a todos!!!

**Comment by Jobbits** [comment]
hola a todos

**Comment by dimicasopcdev** [comment]
Buenos dias para todos, agradecido por la oportunidad!

**Comment by EPAMRGZZProject** [comment]
Hola, suerte a todos y agradezco la oportunidad!

**Comment by davidkaralz** [comment]
Buen dia, muchas gracias por la oportunidad, me gustan estas charlas

**Comment by jmrg-link** [comment]
Genial , gracias por el directo

**Comment by kontroldev** [comment]
Gracias por el directo!!

**Comment by johnnyhuirilef** [comment]
Gracias por el directo

**Comment by Patopm** [comment]
Gracias por el directo

**Comment by J4F3ET** [comment]
Hola a todos, gracias por el directo 😄

**Comment by Sauloopez** [comment]
hola, saludo grande a todos desde Villavicencio Colombia :heart:

**Comment by samucodesh** [comment]
Muy buena charla
