### ISSUE TITLE
Open Source Viernes con PyCon Colombia 

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/selector-rifa#72]
Primero que nada gracias por asistir a nuestro evento, apoyar open-source, muchas gracias por tu tiempo el día de hoy y por ser TÚ!

![OSF Thumbnails](https://github.com/gittogethers/selector-rifa/assets/20666190/d342801b-7d4d-4ec4-8eb5-9ac3b1bf0970)

🚀 Esta página web está desplegada en GitHub Pages utilizando [GitHub Actions](https://github.com/skills/test-with-actions). El flujo de trabajo de Actions obtiene a los participantes de los comentarios en este issue.

🎫 Para participar en el sorteo, inicia sesión en tu cuenta de GitHub. ¿No tienes una? ¡No hay problema! Abre una cuenta gratis y agrega un comentario al final de este issue 👇. No es necesario crear una nueva discusión, simplemente deja un comentario aquí.

🏆 Los premios se sortearán al finalizar la transmisión.

✍🏽 Algunos Términos y Condiciones:

- Participar en este sorteo NO implica tu consentimiento para ser contactado por ningún otro motivo.
- No te agregaremos a nuestra base de datos de marketing (pero si deseas suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/)).
- El premio del sorteo no es transferible ni intercambiable.
- El ganador del premio DEBE enviar un correo electrónico a andreagriffiths11@github.com con su nombre y dirección de correo electrónico.

¡Mucha suerte!

**Comment by cesar-brandon** [comment]
hola a todos 🦆

**Comment by JsMelix** [comment]
Deseo participar

**Comment by Linuxsaurio** [comment]
Surte a todos !! :D

**Comment by gersonja** [comment]
Hola a todos...

**Comment by Migu3low** [comment]
Excelente día para todos!!

**Comment by cristianjonhson** [comment]
Nunca Gano nada :(

**Comment by ghost** [comment]
Hola a todos!!!

**Comment by verordgz25** [comment]
Hola a todos!!

**Comment by cragiraldo** [comment]
Hola buenos dias, espero que esten muy bien

**Comment by davidkaralz** [comment]
Saludos desde Medellin, presente y aprendiendo

**Comment by asyncr** [comment]
Hola, Saludos desde MX ✨🐰

**Comment by CharlyCastrejon** [comment]
¡Suerte! :)

**Comment by jboteros** [comment]
Hola, saludos desde Colombia!

**Comment by mariameneses** [comment]
Hola, me gustaría asistir a esta nueva versión de la PyCon 🤩

**Comment by andresovalle8** [comment]
PyCon Colombia!! éxitos

**Comment by LuisSaucedoo** [comment]
Buenaaaas !

**Comment by duvanbotello** [comment]
¡Nos vemos en PyCon Colombia!

**Comment by verordgz25** [comment]
#PyConColombia

**Comment by henrzven** [comment]
Saludos desde Venezuela <3

**Comment by AngelSanchezT** [comment]
Hola, Gracias por traer a la PyCon Colombia 2024. Ya estoy registrado nos veremos en Medellin

**Comment by gersonja** [comment]
Muy interesante la PyCon Colombia...

**Comment by AndreaGriffiths11** [comment]
Mil gracias a todos por su tiempo ❤️
